// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreRuntimeOptions {
 *     const struct TemporalCoreTelemetryOptions *telemetry;
 *     uint64_t worker_heartbeat_interval_millis;
 * }
 * }
 */
public class TemporalCoreRuntimeOptions {

    TemporalCoreRuntimeOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("telemetry"),
        temporal_sdk_core_c_bridge_h.C_LONG_LONG.withName("worker_heartbeat_interval_millis")
    ).withName("TemporalCoreRuntimeOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout telemetry$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("telemetry"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct TemporalCoreTelemetryOptions *telemetry
     * }
     */
    public static final AddressLayout telemetry$layout() {
        return telemetry$LAYOUT;
    }

    private static final long telemetry$OFFSET = $LAYOUT.byteOffset(groupElement("telemetry"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct TemporalCoreTelemetryOptions *telemetry
     * }
     */
    public static final long telemetry$offset() {
        return telemetry$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreTelemetryOptions *telemetry
     * }
     */
    public static MemorySegment telemetry(MemorySegment struct) {
        return struct.get(telemetry$LAYOUT, telemetry$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreTelemetryOptions *telemetry
     * }
     */
    public static void telemetry(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(telemetry$LAYOUT, telemetry$OFFSET, fieldValue);
    }

    private static final OfLong worker_heartbeat_interval_millis$LAYOUT = (OfLong)$LAYOUT.select(groupElement("worker_heartbeat_interval_millis"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t worker_heartbeat_interval_millis
     * }
     */
    public static final OfLong worker_heartbeat_interval_millis$layout() {
        return worker_heartbeat_interval_millis$LAYOUT;
    }

    private static final long worker_heartbeat_interval_millis$OFFSET = $LAYOUT.byteOffset(groupElement("worker_heartbeat_interval_millis"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t worker_heartbeat_interval_millis
     * }
     */
    public static final long worker_heartbeat_interval_millis$offset() {
        return worker_heartbeat_interval_millis$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t worker_heartbeat_interval_millis
     * }
     */
    public static long worker_heartbeat_interval_millis(MemorySegment struct) {
        return struct.get(worker_heartbeat_interval_millis$LAYOUT, worker_heartbeat_interval_millis$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t worker_heartbeat_interval_millis
     * }
     */
    public static void worker_heartbeat_interval_millis(MemorySegment struct, long fieldValue) {
        struct.set(worker_heartbeat_interval_millis$LAYOUT, worker_heartbeat_interval_millis$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

