// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreWorkerTaskTypes {
 *     bool enable_workflows;
 *     bool enable_local_activities;
 *     bool enable_remote_activities;
 *     bool enable_nexus;
 * }
 * }
 */
public class TemporalCoreWorkerTaskTypes {

    TemporalCoreWorkerTaskTypes() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_BOOL.withName("enable_workflows"),
        temporal_sdk_core_c_bridge_h.C_BOOL.withName("enable_local_activities"),
        temporal_sdk_core_c_bridge_h.C_BOOL.withName("enable_remote_activities"),
        temporal_sdk_core_c_bridge_h.C_BOOL.withName("enable_nexus")
    ).withName("TemporalCoreWorkerTaskTypes");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfBoolean enable_workflows$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enable_workflows"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool enable_workflows
     * }
     */
    public static final OfBoolean enable_workflows$layout() {
        return enable_workflows$LAYOUT;
    }

    private static final long enable_workflows$OFFSET = $LAYOUT.byteOffset(groupElement("enable_workflows"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool enable_workflows
     * }
     */
    public static final long enable_workflows$offset() {
        return enable_workflows$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool enable_workflows
     * }
     */
    public static boolean enable_workflows(MemorySegment struct) {
        return struct.get(enable_workflows$LAYOUT, enable_workflows$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool enable_workflows
     * }
     */
    public static void enable_workflows(MemorySegment struct, boolean fieldValue) {
        struct.set(enable_workflows$LAYOUT, enable_workflows$OFFSET, fieldValue);
    }

    private static final OfBoolean enable_local_activities$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enable_local_activities"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool enable_local_activities
     * }
     */
    public static final OfBoolean enable_local_activities$layout() {
        return enable_local_activities$LAYOUT;
    }

    private static final long enable_local_activities$OFFSET = $LAYOUT.byteOffset(groupElement("enable_local_activities"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool enable_local_activities
     * }
     */
    public static final long enable_local_activities$offset() {
        return enable_local_activities$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool enable_local_activities
     * }
     */
    public static boolean enable_local_activities(MemorySegment struct) {
        return struct.get(enable_local_activities$LAYOUT, enable_local_activities$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool enable_local_activities
     * }
     */
    public static void enable_local_activities(MemorySegment struct, boolean fieldValue) {
        struct.set(enable_local_activities$LAYOUT, enable_local_activities$OFFSET, fieldValue);
    }

    private static final OfBoolean enable_remote_activities$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enable_remote_activities"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool enable_remote_activities
     * }
     */
    public static final OfBoolean enable_remote_activities$layout() {
        return enable_remote_activities$LAYOUT;
    }

    private static final long enable_remote_activities$OFFSET = $LAYOUT.byteOffset(groupElement("enable_remote_activities"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool enable_remote_activities
     * }
     */
    public static final long enable_remote_activities$offset() {
        return enable_remote_activities$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool enable_remote_activities
     * }
     */
    public static boolean enable_remote_activities(MemorySegment struct) {
        return struct.get(enable_remote_activities$LAYOUT, enable_remote_activities$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool enable_remote_activities
     * }
     */
    public static void enable_remote_activities(MemorySegment struct, boolean fieldValue) {
        struct.set(enable_remote_activities$LAYOUT, enable_remote_activities$OFFSET, fieldValue);
    }

    private static final OfBoolean enable_nexus$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enable_nexus"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool enable_nexus
     * }
     */
    public static final OfBoolean enable_nexus$layout() {
        return enable_nexus$LAYOUT;
    }

    private static final long enable_nexus$OFFSET = $LAYOUT.byteOffset(groupElement("enable_nexus"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool enable_nexus
     * }
     */
    public static final long enable_nexus$offset() {
        return enable_nexus$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool enable_nexus
     * }
     */
    public static boolean enable_nexus(MemorySegment struct) {
        return struct.get(enable_nexus$LAYOUT, enable_nexus$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool enable_nexus
     * }
     */
    public static void enable_nexus(MemorySegment struct, boolean fieldValue) {
        struct.set(enable_nexus$LAYOUT, enable_nexus$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

