// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * union TemporalCoreMetricAttributeValue {
 *     struct TemporalCoreByteArrayRef string_value;
 *     int64_t int_value;
 *     double float_value;
 *     bool bool_value;
 * }
 * }
 */
public class TemporalCoreMetricAttributeValue {

    TemporalCoreMetricAttributeValue() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
        TemporalCoreByteArrayRef.layout().withName("string_value"),
        temporal_sdk_core_c_bridge_h.C_LONG_LONG.withName("int_value"),
        temporal_sdk_core_c_bridge_h.C_DOUBLE.withName("float_value"),
        temporal_sdk_core_c_bridge_h.C_BOOL.withName("bool_value")
    ).withName("TemporalCoreMetricAttributeValue");

    /**
     * The layout of this union
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout string_value$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("string_value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef string_value
     * }
     */
    public static final GroupLayout string_value$layout() {
        return string_value$LAYOUT;
    }

    private static final long string_value$OFFSET = $LAYOUT.byteOffset(groupElement("string_value"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef string_value
     * }
     */
    public static final long string_value$offset() {
        return string_value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef string_value
     * }
     */
    public static MemorySegment string_value(MemorySegment union) {
        return union.asSlice(string_value$OFFSET, string_value$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef string_value
     * }
     */
    public static void string_value(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, string_value$OFFSET, string_value$LAYOUT.byteSize());
    }

    private static final OfLong int_value$LAYOUT = (OfLong)$LAYOUT.select(groupElement("int_value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t int_value
     * }
     */
    public static final OfLong int_value$layout() {
        return int_value$LAYOUT;
    }

    private static final long int_value$OFFSET = $LAYOUT.byteOffset(groupElement("int_value"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t int_value
     * }
     */
    public static final long int_value$offset() {
        return int_value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t int_value
     * }
     */
    public static long int_value(MemorySegment union) {
        return union.get(int_value$LAYOUT, int_value$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t int_value
     * }
     */
    public static void int_value(MemorySegment union, long fieldValue) {
        union.set(int_value$LAYOUT, int_value$OFFSET, fieldValue);
    }

    private static final OfDouble float_value$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("float_value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double float_value
     * }
     */
    public static final OfDouble float_value$layout() {
        return float_value$LAYOUT;
    }

    private static final long float_value$OFFSET = $LAYOUT.byteOffset(groupElement("float_value"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double float_value
     * }
     */
    public static final long float_value$offset() {
        return float_value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double float_value
     * }
     */
    public static double float_value(MemorySegment union) {
        return union.get(float_value$LAYOUT, float_value$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double float_value
     * }
     */
    public static void float_value(MemorySegment union, double fieldValue) {
        union.set(float_value$LAYOUT, float_value$OFFSET, fieldValue);
    }

    private static final OfBoolean bool_value$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("bool_value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool bool_value
     * }
     */
    public static final OfBoolean bool_value$layout() {
        return bool_value$LAYOUT;
    }

    private static final long bool_value$OFFSET = $LAYOUT.byteOffset(groupElement("bool_value"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool bool_value
     * }
     */
    public static final long bool_value$offset() {
        return bool_value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool bool_value
     * }
     */
    public static boolean bool_value(MemorySegment union) {
        return union.get(bool_value$LAYOUT, bool_value$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool bool_value
     * }
     */
    public static void bool_value(MemorySegment union, boolean fieldValue) {
        union.set(bool_value$LAYOUT, bool_value$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this union
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

