// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreMetricsOptions {
 *     const struct TemporalCoreOpenTelemetryOptions *opentelemetry;
 *     const struct TemporalCorePrometheusOptions *prometheus;
 *     const struct TemporalCoreCustomMetricMeter *custom_meter;
 *     bool attach_service_name;
 *     TemporalCoreNewlineDelimitedMapRef global_tags;
 *     struct TemporalCoreByteArrayRef metric_prefix;
 * }
 * }
 */
public class TemporalCoreMetricsOptions {

    TemporalCoreMetricsOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("opentelemetry"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("prometheus"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("custom_meter"),
        temporal_sdk_core_c_bridge_h.C_BOOL.withName("attach_service_name"),
        MemoryLayout.paddingLayout(7),
        TemporalCoreByteArrayRef.layout().withName("global_tags"),
        TemporalCoreByteArrayRef.layout().withName("metric_prefix")
    ).withName("TemporalCoreMetricsOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout opentelemetry$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("opentelemetry"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct TemporalCoreOpenTelemetryOptions *opentelemetry
     * }
     */
    public static final AddressLayout opentelemetry$layout() {
        return opentelemetry$LAYOUT;
    }

    private static final long opentelemetry$OFFSET = $LAYOUT.byteOffset(groupElement("opentelemetry"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct TemporalCoreOpenTelemetryOptions *opentelemetry
     * }
     */
    public static final long opentelemetry$offset() {
        return opentelemetry$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreOpenTelemetryOptions *opentelemetry
     * }
     */
    public static MemorySegment opentelemetry(MemorySegment struct) {
        return struct.get(opentelemetry$LAYOUT, opentelemetry$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreOpenTelemetryOptions *opentelemetry
     * }
     */
    public static void opentelemetry(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(opentelemetry$LAYOUT, opentelemetry$OFFSET, fieldValue);
    }

    private static final AddressLayout prometheus$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("prometheus"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct TemporalCorePrometheusOptions *prometheus
     * }
     */
    public static final AddressLayout prometheus$layout() {
        return prometheus$LAYOUT;
    }

    private static final long prometheus$OFFSET = $LAYOUT.byteOffset(groupElement("prometheus"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct TemporalCorePrometheusOptions *prometheus
     * }
     */
    public static final long prometheus$offset() {
        return prometheus$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct TemporalCorePrometheusOptions *prometheus
     * }
     */
    public static MemorySegment prometheus(MemorySegment struct) {
        return struct.get(prometheus$LAYOUT, prometheus$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct TemporalCorePrometheusOptions *prometheus
     * }
     */
    public static void prometheus(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(prometheus$LAYOUT, prometheus$OFFSET, fieldValue);
    }

    private static final AddressLayout custom_meter$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("custom_meter"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct TemporalCoreCustomMetricMeter *custom_meter
     * }
     */
    public static final AddressLayout custom_meter$layout() {
        return custom_meter$LAYOUT;
    }

    private static final long custom_meter$OFFSET = $LAYOUT.byteOffset(groupElement("custom_meter"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct TemporalCoreCustomMetricMeter *custom_meter
     * }
     */
    public static final long custom_meter$offset() {
        return custom_meter$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreCustomMetricMeter *custom_meter
     * }
     */
    public static MemorySegment custom_meter(MemorySegment struct) {
        return struct.get(custom_meter$LAYOUT, custom_meter$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreCustomMetricMeter *custom_meter
     * }
     */
    public static void custom_meter(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(custom_meter$LAYOUT, custom_meter$OFFSET, fieldValue);
    }

    private static final OfBoolean attach_service_name$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("attach_service_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool attach_service_name
     * }
     */
    public static final OfBoolean attach_service_name$layout() {
        return attach_service_name$LAYOUT;
    }

    private static final long attach_service_name$OFFSET = $LAYOUT.byteOffset(groupElement("attach_service_name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool attach_service_name
     * }
     */
    public static final long attach_service_name$offset() {
        return attach_service_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool attach_service_name
     * }
     */
    public static boolean attach_service_name(MemorySegment struct) {
        return struct.get(attach_service_name$LAYOUT, attach_service_name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool attach_service_name
     * }
     */
    public static void attach_service_name(MemorySegment struct, boolean fieldValue) {
        struct.set(attach_service_name$LAYOUT, attach_service_name$OFFSET, fieldValue);
    }

    private static final GroupLayout global_tags$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("global_tags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreNewlineDelimitedMapRef global_tags
     * }
     */
    public static final GroupLayout global_tags$layout() {
        return global_tags$LAYOUT;
    }

    private static final long global_tags$OFFSET = $LAYOUT.byteOffset(groupElement("global_tags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreNewlineDelimitedMapRef global_tags
     * }
     */
    public static final long global_tags$offset() {
        return global_tags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreNewlineDelimitedMapRef global_tags
     * }
     */
    public static MemorySegment global_tags(MemorySegment struct) {
        return struct.asSlice(global_tags$OFFSET, global_tags$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreNewlineDelimitedMapRef global_tags
     * }
     */
    public static void global_tags(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, global_tags$OFFSET, global_tags$LAYOUT.byteSize());
    }

    private static final GroupLayout metric_prefix$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("metric_prefix"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef metric_prefix
     * }
     */
    public static final GroupLayout metric_prefix$layout() {
        return metric_prefix$LAYOUT;
    }

    private static final long metric_prefix$OFFSET = $LAYOUT.byteOffset(groupElement("metric_prefix"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef metric_prefix
     * }
     */
    public static final long metric_prefix$offset() {
        return metric_prefix$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef metric_prefix
     * }
     */
    public static MemorySegment metric_prefix(MemorySegment struct) {
        return struct.asSlice(metric_prefix$OFFSET, metric_prefix$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef metric_prefix
     * }
     */
    public static void metric_prefix(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, metric_prefix$OFFSET, metric_prefix$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

