// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef uintptr_t (*TemporalCoreCustomSlotSupplierTryReserveCallback)(const struct TemporalCoreSlotReserveCtx {
 *     enum TemporalCoreSlotKindType slot_type;
 *     struct TemporalCoreByteArrayRef task_queue;
 *     struct TemporalCoreByteArrayRef worker_identity;
 *     struct TemporalCoreByteArrayRef worker_build_id;
 *     bool is_sticky;
 * } *, void *)
 * }
 */
public final class TemporalCoreCustomSlotSupplierTryReserveCallback {

    private TemporalCoreCustomSlotSupplierTryReserveCallback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        long apply(MemorySegment ctx, MemorySegment user_data);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        temporal_sdk_core_c_bridge_h.C_LONG,
        temporal_sdk_core_c_bridge_h.C_POINTER,
        temporal_sdk_core_c_bridge_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = temporal_sdk_core_c_bridge_h.upcallHandle(TemporalCoreCustomSlotSupplierTryReserveCallback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(TemporalCoreCustomSlotSupplierTryReserveCallback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static long invoke(MemorySegment funcPtr, MemorySegment ctx, MemorySegment user_data) {
        try {
            return (long) DOWN$MH.invokeExact(funcPtr, ctx, user_data);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

