// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreTunerHolder {
 *     struct TemporalCoreSlotSupplier workflow_slot_supplier;
 *     struct TemporalCoreSlotSupplier activity_slot_supplier;
 *     struct TemporalCoreSlotSupplier local_activity_slot_supplier;
 *     struct TemporalCoreSlotSupplier nexus_task_slot_supplier;
 * }
 * }
 */
public class TemporalCoreTunerHolder {

    TemporalCoreTunerHolder() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TemporalCoreSlotSupplier.layout().withName("workflow_slot_supplier"),
        TemporalCoreSlotSupplier.layout().withName("activity_slot_supplier"),
        TemporalCoreSlotSupplier.layout().withName("local_activity_slot_supplier"),
        TemporalCoreSlotSupplier.layout().withName("nexus_task_slot_supplier")
    ).withName("TemporalCoreTunerHolder");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout workflow_slot_supplier$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("workflow_slot_supplier"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreSlotSupplier workflow_slot_supplier
     * }
     */
    public static final GroupLayout workflow_slot_supplier$layout() {
        return workflow_slot_supplier$LAYOUT;
    }

    private static final long workflow_slot_supplier$OFFSET = $LAYOUT.byteOffset(groupElement("workflow_slot_supplier"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreSlotSupplier workflow_slot_supplier
     * }
     */
    public static final long workflow_slot_supplier$offset() {
        return workflow_slot_supplier$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreSlotSupplier workflow_slot_supplier
     * }
     */
    public static MemorySegment workflow_slot_supplier(MemorySegment struct) {
        return struct.asSlice(workflow_slot_supplier$OFFSET, workflow_slot_supplier$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreSlotSupplier workflow_slot_supplier
     * }
     */
    public static void workflow_slot_supplier(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, workflow_slot_supplier$OFFSET, workflow_slot_supplier$LAYOUT.byteSize());
    }

    private static final GroupLayout activity_slot_supplier$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("activity_slot_supplier"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreSlotSupplier activity_slot_supplier
     * }
     */
    public static final GroupLayout activity_slot_supplier$layout() {
        return activity_slot_supplier$LAYOUT;
    }

    private static final long activity_slot_supplier$OFFSET = $LAYOUT.byteOffset(groupElement("activity_slot_supplier"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreSlotSupplier activity_slot_supplier
     * }
     */
    public static final long activity_slot_supplier$offset() {
        return activity_slot_supplier$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreSlotSupplier activity_slot_supplier
     * }
     */
    public static MemorySegment activity_slot_supplier(MemorySegment struct) {
        return struct.asSlice(activity_slot_supplier$OFFSET, activity_slot_supplier$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreSlotSupplier activity_slot_supplier
     * }
     */
    public static void activity_slot_supplier(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, activity_slot_supplier$OFFSET, activity_slot_supplier$LAYOUT.byteSize());
    }

    private static final GroupLayout local_activity_slot_supplier$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("local_activity_slot_supplier"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreSlotSupplier local_activity_slot_supplier
     * }
     */
    public static final GroupLayout local_activity_slot_supplier$layout() {
        return local_activity_slot_supplier$LAYOUT;
    }

    private static final long local_activity_slot_supplier$OFFSET = $LAYOUT.byteOffset(groupElement("local_activity_slot_supplier"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreSlotSupplier local_activity_slot_supplier
     * }
     */
    public static final long local_activity_slot_supplier$offset() {
        return local_activity_slot_supplier$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreSlotSupplier local_activity_slot_supplier
     * }
     */
    public static MemorySegment local_activity_slot_supplier(MemorySegment struct) {
        return struct.asSlice(local_activity_slot_supplier$OFFSET, local_activity_slot_supplier$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreSlotSupplier local_activity_slot_supplier
     * }
     */
    public static void local_activity_slot_supplier(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, local_activity_slot_supplier$OFFSET, local_activity_slot_supplier$LAYOUT.byteSize());
    }

    private static final GroupLayout nexus_task_slot_supplier$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("nexus_task_slot_supplier"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreSlotSupplier nexus_task_slot_supplier
     * }
     */
    public static final GroupLayout nexus_task_slot_supplier$layout() {
        return nexus_task_slot_supplier$LAYOUT;
    }

    private static final long nexus_task_slot_supplier$OFFSET = $LAYOUT.byteOffset(groupElement("nexus_task_slot_supplier"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreSlotSupplier nexus_task_slot_supplier
     * }
     */
    public static final long nexus_task_slot_supplier$offset() {
        return nexus_task_slot_supplier$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreSlotSupplier nexus_task_slot_supplier
     * }
     */
    public static MemorySegment nexus_task_slot_supplier(MemorySegment struct) {
        return struct.asSlice(nexus_task_slot_supplier$OFFSET, nexus_task_slot_supplier$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreSlotSupplier nexus_task_slot_supplier
     * }
     */
    public static void nexus_task_slot_supplier(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, nexus_task_slot_supplier$OFFSET, nexus_task_slot_supplier$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

