// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCorePollerBehaviorSimpleMaximum {
 *     uintptr_t simple_maximum;
 * }
 * }
 */
public class TemporalCorePollerBehaviorSimpleMaximum {

    TemporalCorePollerBehaviorSimpleMaximum() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_LONG.withName("simple_maximum")
    ).withName("TemporalCorePollerBehaviorSimpleMaximum");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong simple_maximum$LAYOUT = (OfLong)$LAYOUT.select(groupElement("simple_maximum"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uintptr_t simple_maximum
     * }
     */
    public static final OfLong simple_maximum$layout() {
        return simple_maximum$LAYOUT;
    }

    private static final long simple_maximum$OFFSET = $LAYOUT.byteOffset(groupElement("simple_maximum"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uintptr_t simple_maximum
     * }
     */
    public static final long simple_maximum$offset() {
        return simple_maximum$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uintptr_t simple_maximum
     * }
     */
    public static long simple_maximum(MemorySegment struct) {
        return struct.get(simple_maximum$LAYOUT, simple_maximum$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uintptr_t simple_maximum
     * }
     */
    public static void simple_maximum(MemorySegment struct, long fieldValue) {
        struct.set(simple_maximum$LAYOUT, simple_maximum$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

