// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCorePrometheusOptions {
 *     struct TemporalCoreByteArrayRef bind_address;
 *     bool counters_total_suffix;
 *     bool unit_suffix;
 *     bool durations_as_seconds;
 *     TemporalCoreNewlineDelimitedMapRef histogram_bucket_overrides;
 * }
 * }
 */
public class TemporalCorePrometheusOptions {

    TemporalCorePrometheusOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TemporalCoreByteArrayRef.layout().withName("bind_address"),
        temporal_sdk_core_c_bridge_h.C_BOOL.withName("counters_total_suffix"),
        temporal_sdk_core_c_bridge_h.C_BOOL.withName("unit_suffix"),
        temporal_sdk_core_c_bridge_h.C_BOOL.withName("durations_as_seconds"),
        MemoryLayout.paddingLayout(5),
        TemporalCoreByteArrayRef.layout().withName("histogram_bucket_overrides")
    ).withName("TemporalCorePrometheusOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout bind_address$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("bind_address"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef bind_address
     * }
     */
    public static final GroupLayout bind_address$layout() {
        return bind_address$LAYOUT;
    }

    private static final long bind_address$OFFSET = $LAYOUT.byteOffset(groupElement("bind_address"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef bind_address
     * }
     */
    public static final long bind_address$offset() {
        return bind_address$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef bind_address
     * }
     */
    public static MemorySegment bind_address(MemorySegment struct) {
        return struct.asSlice(bind_address$OFFSET, bind_address$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef bind_address
     * }
     */
    public static void bind_address(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, bind_address$OFFSET, bind_address$LAYOUT.byteSize());
    }

    private static final OfBoolean counters_total_suffix$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("counters_total_suffix"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool counters_total_suffix
     * }
     */
    public static final OfBoolean counters_total_suffix$layout() {
        return counters_total_suffix$LAYOUT;
    }

    private static final long counters_total_suffix$OFFSET = $LAYOUT.byteOffset(groupElement("counters_total_suffix"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool counters_total_suffix
     * }
     */
    public static final long counters_total_suffix$offset() {
        return counters_total_suffix$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool counters_total_suffix
     * }
     */
    public static boolean counters_total_suffix(MemorySegment struct) {
        return struct.get(counters_total_suffix$LAYOUT, counters_total_suffix$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool counters_total_suffix
     * }
     */
    public static void counters_total_suffix(MemorySegment struct, boolean fieldValue) {
        struct.set(counters_total_suffix$LAYOUT, counters_total_suffix$OFFSET, fieldValue);
    }

    private static final OfBoolean unit_suffix$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("unit_suffix"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool unit_suffix
     * }
     */
    public static final OfBoolean unit_suffix$layout() {
        return unit_suffix$LAYOUT;
    }

    private static final long unit_suffix$OFFSET = $LAYOUT.byteOffset(groupElement("unit_suffix"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool unit_suffix
     * }
     */
    public static final long unit_suffix$offset() {
        return unit_suffix$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool unit_suffix
     * }
     */
    public static boolean unit_suffix(MemorySegment struct) {
        return struct.get(unit_suffix$LAYOUT, unit_suffix$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool unit_suffix
     * }
     */
    public static void unit_suffix(MemorySegment struct, boolean fieldValue) {
        struct.set(unit_suffix$LAYOUT, unit_suffix$OFFSET, fieldValue);
    }

    private static final OfBoolean durations_as_seconds$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("durations_as_seconds"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool durations_as_seconds
     * }
     */
    public static final OfBoolean durations_as_seconds$layout() {
        return durations_as_seconds$LAYOUT;
    }

    private static final long durations_as_seconds$OFFSET = $LAYOUT.byteOffset(groupElement("durations_as_seconds"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool durations_as_seconds
     * }
     */
    public static final long durations_as_seconds$offset() {
        return durations_as_seconds$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool durations_as_seconds
     * }
     */
    public static boolean durations_as_seconds(MemorySegment struct) {
        return struct.get(durations_as_seconds$LAYOUT, durations_as_seconds$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool durations_as_seconds
     * }
     */
    public static void durations_as_seconds(MemorySegment struct, boolean fieldValue) {
        struct.set(durations_as_seconds$LAYOUT, durations_as_seconds$OFFSET, fieldValue);
    }

    private static final GroupLayout histogram_bucket_overrides$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("histogram_bucket_overrides"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreNewlineDelimitedMapRef histogram_bucket_overrides
     * }
     */
    public static final GroupLayout histogram_bucket_overrides$layout() {
        return histogram_bucket_overrides$LAYOUT;
    }

    private static final long histogram_bucket_overrides$OFFSET = $LAYOUT.byteOffset(groupElement("histogram_bucket_overrides"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreNewlineDelimitedMapRef histogram_bucket_overrides
     * }
     */
    public static final long histogram_bucket_overrides$offset() {
        return histogram_bucket_overrides$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreNewlineDelimitedMapRef histogram_bucket_overrides
     * }
     */
    public static MemorySegment histogram_bucket_overrides(MemorySegment struct) {
        return struct.asSlice(histogram_bucket_overrides$OFFSET, histogram_bucket_overrides$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreNewlineDelimitedMapRef histogram_bucket_overrides
     * }
     */
    public static void histogram_bucket_overrides(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, histogram_bucket_overrides$OFFSET, histogram_bucket_overrides$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

