// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreTelemetryOptions {
 *     const struct TemporalCoreLoggingOptions *logging;
 *     const struct TemporalCoreMetricsOptions *metrics;
 * }
 * }
 */
public class TemporalCoreTelemetryOptions {

    TemporalCoreTelemetryOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("logging"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("metrics")
    ).withName("TemporalCoreTelemetryOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout logging$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("logging"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct TemporalCoreLoggingOptions *logging
     * }
     */
    public static final AddressLayout logging$layout() {
        return logging$LAYOUT;
    }

    private static final long logging$OFFSET = $LAYOUT.byteOffset(groupElement("logging"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct TemporalCoreLoggingOptions *logging
     * }
     */
    public static final long logging$offset() {
        return logging$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreLoggingOptions *logging
     * }
     */
    public static MemorySegment logging(MemorySegment struct) {
        return struct.get(logging$LAYOUT, logging$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreLoggingOptions *logging
     * }
     */
    public static void logging(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(logging$LAYOUT, logging$OFFSET, fieldValue);
    }

    private static final AddressLayout metrics$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("metrics"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct TemporalCoreMetricsOptions *metrics
     * }
     */
    public static final AddressLayout metrics$layout() {
        return metrics$LAYOUT;
    }

    private static final long metrics$OFFSET = $LAYOUT.byteOffset(groupElement("metrics"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct TemporalCoreMetricsOptions *metrics
     * }
     */
    public static final long metrics$offset() {
        return metrics$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreMetricsOptions *metrics
     * }
     */
    public static MemorySegment metrics(MemorySegment struct) {
        return struct.get(metrics$LAYOUT, metrics$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreMetricsOptions *metrics
     * }
     */
    public static void metrics(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(metrics$LAYOUT, metrics$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

