// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreClientKeepAliveOptions {
 *     uint64_t interval_millis;
 *     uint64_t timeout_millis;
 * }
 * }
 */
public class TemporalCoreClientKeepAliveOptions {

    TemporalCoreClientKeepAliveOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_LONG_LONG.withName("interval_millis"),
        temporal_sdk_core_c_bridge_h.C_LONG_LONG.withName("timeout_millis")
    ).withName("TemporalCoreClientKeepAliveOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong interval_millis$LAYOUT = (OfLong)$LAYOUT.select(groupElement("interval_millis"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t interval_millis
     * }
     */
    public static final OfLong interval_millis$layout() {
        return interval_millis$LAYOUT;
    }

    private static final long interval_millis$OFFSET = $LAYOUT.byteOffset(groupElement("interval_millis"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t interval_millis
     * }
     */
    public static final long interval_millis$offset() {
        return interval_millis$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t interval_millis
     * }
     */
    public static long interval_millis(MemorySegment struct) {
        return struct.get(interval_millis$LAYOUT, interval_millis$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t interval_millis
     * }
     */
    public static void interval_millis(MemorySegment struct, long fieldValue) {
        struct.set(interval_millis$LAYOUT, interval_millis$OFFSET, fieldValue);
    }

    private static final OfLong timeout_millis$LAYOUT = (OfLong)$LAYOUT.select(groupElement("timeout_millis"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t timeout_millis
     * }
     */
    public static final OfLong timeout_millis$layout() {
        return timeout_millis$LAYOUT;
    }

    private static final long timeout_millis$OFFSET = $LAYOUT.byteOffset(groupElement("timeout_millis"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t timeout_millis
     * }
     */
    public static final long timeout_millis$offset() {
        return timeout_millis$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t timeout_millis
     * }
     */
    public static long timeout_millis(MemorySegment struct) {
        return struct.get(timeout_millis$LAYOUT, timeout_millis$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t timeout_millis
     * }
     */
    public static void timeout_millis(MemorySegment struct, long fieldValue) {
        struct.set(timeout_millis$LAYOUT, timeout_millis$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

