// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreSlotInfo {
 *     TemporalCoreSlotInfo_Tag tag;
 *     union {
 *         TemporalCoreWorkflowSlotInfo_Body workflow_slot_info;
 *         TemporalCoreActivitySlotInfo_Body activity_slot_info;
 *         TemporalCoreLocalActivitySlotInfo_Body local_activity_slot_info;
 *         TemporalCoreNexusSlotInfo_Body nexus_slot_info;
 *     };
 * }
 * }
 */
public class TemporalCoreSlotInfo {

    TemporalCoreSlotInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_INT.withName("tag"),
        MemoryLayout.paddingLayout(4),
        MemoryLayout.unionLayout(
            TemporalCoreWorkflowSlotInfo_Body.layout().withName("workflow_slot_info"),
            TemporalCoreActivitySlotInfo_Body.layout().withName("activity_slot_info"),
            TemporalCoreLocalActivitySlotInfo_Body.layout().withName("local_activity_slot_info"),
            TemporalCoreNexusSlotInfo_Body.layout().withName("nexus_slot_info")
        ).withName("$anon$628:3")
    ).withName("TemporalCoreSlotInfo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt tag$LAYOUT = (OfInt)$LAYOUT.select(groupElement("tag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreSlotInfo_Tag tag
     * }
     */
    public static final OfInt tag$layout() {
        return tag$LAYOUT;
    }

    private static final long tag$OFFSET = $LAYOUT.byteOffset(groupElement("tag"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreSlotInfo_Tag tag
     * }
     */
    public static final long tag$offset() {
        return tag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreSlotInfo_Tag tag
     * }
     */
    public static int tag(MemorySegment struct) {
        return struct.get(tag$LAYOUT, tag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreSlotInfo_Tag tag
     * }
     */
    public static void tag(MemorySegment struct, int fieldValue) {
        struct.set(tag$LAYOUT, tag$OFFSET, fieldValue);
    }

    private static final GroupLayout workflow_slot_info$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$628:3"), groupElement("workflow_slot_info"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreWorkflowSlotInfo_Body workflow_slot_info
     * }
     */
    public static final GroupLayout workflow_slot_info$layout() {
        return workflow_slot_info$LAYOUT;
    }

    private static final long workflow_slot_info$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$628:3"), groupElement("workflow_slot_info"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreWorkflowSlotInfo_Body workflow_slot_info
     * }
     */
    public static final long workflow_slot_info$offset() {
        return workflow_slot_info$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreWorkflowSlotInfo_Body workflow_slot_info
     * }
     */
    public static MemorySegment workflow_slot_info(MemorySegment struct) {
        return struct.asSlice(workflow_slot_info$OFFSET, workflow_slot_info$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreWorkflowSlotInfo_Body workflow_slot_info
     * }
     */
    public static void workflow_slot_info(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, workflow_slot_info$OFFSET, workflow_slot_info$LAYOUT.byteSize());
    }

    private static final GroupLayout activity_slot_info$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$628:3"), groupElement("activity_slot_info"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreActivitySlotInfo_Body activity_slot_info
     * }
     */
    public static final GroupLayout activity_slot_info$layout() {
        return activity_slot_info$LAYOUT;
    }

    private static final long activity_slot_info$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$628:3"), groupElement("activity_slot_info"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreActivitySlotInfo_Body activity_slot_info
     * }
     */
    public static final long activity_slot_info$offset() {
        return activity_slot_info$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreActivitySlotInfo_Body activity_slot_info
     * }
     */
    public static MemorySegment activity_slot_info(MemorySegment struct) {
        return struct.asSlice(activity_slot_info$OFFSET, activity_slot_info$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreActivitySlotInfo_Body activity_slot_info
     * }
     */
    public static void activity_slot_info(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, activity_slot_info$OFFSET, activity_slot_info$LAYOUT.byteSize());
    }

    private static final GroupLayout local_activity_slot_info$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$628:3"), groupElement("local_activity_slot_info"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreLocalActivitySlotInfo_Body local_activity_slot_info
     * }
     */
    public static final GroupLayout local_activity_slot_info$layout() {
        return local_activity_slot_info$LAYOUT;
    }

    private static final long local_activity_slot_info$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$628:3"), groupElement("local_activity_slot_info"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreLocalActivitySlotInfo_Body local_activity_slot_info
     * }
     */
    public static final long local_activity_slot_info$offset() {
        return local_activity_slot_info$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreLocalActivitySlotInfo_Body local_activity_slot_info
     * }
     */
    public static MemorySegment local_activity_slot_info(MemorySegment struct) {
        return struct.asSlice(local_activity_slot_info$OFFSET, local_activity_slot_info$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreLocalActivitySlotInfo_Body local_activity_slot_info
     * }
     */
    public static void local_activity_slot_info(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, local_activity_slot_info$OFFSET, local_activity_slot_info$LAYOUT.byteSize());
    }

    private static final GroupLayout nexus_slot_info$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$628:3"), groupElement("nexus_slot_info"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreNexusSlotInfo_Body nexus_slot_info
     * }
     */
    public static final GroupLayout nexus_slot_info$layout() {
        return nexus_slot_info$LAYOUT;
    }

    private static final long nexus_slot_info$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$628:3"), groupElement("nexus_slot_info"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreNexusSlotInfo_Body nexus_slot_info
     * }
     */
    public static final long nexus_slot_info$offset() {
        return nexus_slot_info$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreNexusSlotInfo_Body nexus_slot_info
     * }
     */
    public static MemorySegment nexus_slot_info(MemorySegment struct) {
        return struct.asSlice(nexus_slot_info$OFFSET, nexus_slot_info$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreNexusSlotInfo_Body nexus_slot_info
     * }
     */
    public static void nexus_slot_info(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, nexus_slot_info$OFFSET, nexus_slot_info$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

