// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreSlotSupplier {
 *     TemporalCoreSlotSupplier_Tag tag;
 *     union {
 *         struct {
 *             struct TemporalCoreFixedSizeSlotSupplier fixed_size;
 *         };
 *         struct {
 *             struct TemporalCoreResourceBasedSlotSupplier resource_based;
 *         };
 *         struct {
 *             struct TemporalCoreCustomSlotSupplierCallbacksImpl custom;
 *         };
 *     };
 * }
 * }
 */
public class TemporalCoreSlotSupplier {

    TemporalCoreSlotSupplier() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_INT.withName("tag"),
        MemoryLayout.paddingLayout(4),
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                TemporalCoreFixedSizeSlotSupplier.layout().withName("fixed_size")
            ).withName("$anon$735:5"),
            MemoryLayout.structLayout(
                TemporalCoreResourceBasedSlotSupplier.layout().withName("resource_based")
            ).withName("$anon$738:5"),
            MemoryLayout.structLayout(
                TemporalCoreCustomSlotSupplierCallbacksImpl.layout().withName("custom")
            ).withName("$anon$741:5")
        ).withName("$anon$734:3")
    ).withName("TemporalCoreSlotSupplier");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt tag$LAYOUT = (OfInt)$LAYOUT.select(groupElement("tag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreSlotSupplier_Tag tag
     * }
     */
    public static final OfInt tag$layout() {
        return tag$LAYOUT;
    }

    private static final long tag$OFFSET = $LAYOUT.byteOffset(groupElement("tag"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreSlotSupplier_Tag tag
     * }
     */
    public static final long tag$offset() {
        return tag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreSlotSupplier_Tag tag
     * }
     */
    public static int tag(MemorySegment struct) {
        return struct.get(tag$LAYOUT, tag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreSlotSupplier_Tag tag
     * }
     */
    public static void tag(MemorySegment struct, int fieldValue) {
        struct.set(tag$LAYOUT, tag$OFFSET, fieldValue);
    }

    private static final GroupLayout fixed_size$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$734:3"), groupElement("$anon$735:5"), groupElement("fixed_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreFixedSizeSlotSupplier fixed_size
     * }
     */
    public static final GroupLayout fixed_size$layout() {
        return fixed_size$LAYOUT;
    }

    private static final long fixed_size$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$734:3"), groupElement("$anon$735:5"), groupElement("fixed_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreFixedSizeSlotSupplier fixed_size
     * }
     */
    public static final long fixed_size$offset() {
        return fixed_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreFixedSizeSlotSupplier fixed_size
     * }
     */
    public static MemorySegment fixed_size(MemorySegment struct) {
        return struct.asSlice(fixed_size$OFFSET, fixed_size$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreFixedSizeSlotSupplier fixed_size
     * }
     */
    public static void fixed_size(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, fixed_size$OFFSET, fixed_size$LAYOUT.byteSize());
    }

    private static final GroupLayout resource_based$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$734:3"), groupElement("$anon$738:5"), groupElement("resource_based"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreResourceBasedSlotSupplier resource_based
     * }
     */
    public static final GroupLayout resource_based$layout() {
        return resource_based$LAYOUT;
    }

    private static final long resource_based$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$734:3"), groupElement("$anon$738:5"), groupElement("resource_based"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreResourceBasedSlotSupplier resource_based
     * }
     */
    public static final long resource_based$offset() {
        return resource_based$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreResourceBasedSlotSupplier resource_based
     * }
     */
    public static MemorySegment resource_based(MemorySegment struct) {
        return struct.asSlice(resource_based$OFFSET, resource_based$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreResourceBasedSlotSupplier resource_based
     * }
     */
    public static void resource_based(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, resource_based$OFFSET, resource_based$LAYOUT.byteSize());
    }

    private static final GroupLayout custom$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$734:3"), groupElement("$anon$741:5"), groupElement("custom"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreCustomSlotSupplierCallbacksImpl custom
     * }
     */
    public static final GroupLayout custom$layout() {
        return custom$LAYOUT;
    }

    private static final long custom$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$734:3"), groupElement("$anon$741:5"), groupElement("custom"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreCustomSlotSupplierCallbacksImpl custom
     * }
     */
    public static final long custom$offset() {
        return custom$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreCustomSlotSupplierCallbacksImpl custom
     * }
     */
    public static MemorySegment custom(MemorySegment struct) {
        return struct.asSlice(custom$OFFSET, custom$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreCustomSlotSupplierCallbacksImpl custom
     * }
     */
    public static void custom(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, custom$OFFSET, custom$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

