// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCorePollerBehaviorAutoscaling {
 *     uintptr_t minimum;
 *     uintptr_t maximum;
 *     uintptr_t initial;
 * }
 * }
 */
public class TemporalCorePollerBehaviorAutoscaling {

    TemporalCorePollerBehaviorAutoscaling() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_LONG.withName("minimum"),
        temporal_sdk_core_c_bridge_h.C_LONG.withName("maximum"),
        temporal_sdk_core_c_bridge_h.C_LONG.withName("initial")
    ).withName("TemporalCorePollerBehaviorAutoscaling");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong minimum$LAYOUT = (OfLong)$LAYOUT.select(groupElement("minimum"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uintptr_t minimum
     * }
     */
    public static final OfLong minimum$layout() {
        return minimum$LAYOUT;
    }

    private static final long minimum$OFFSET = $LAYOUT.byteOffset(groupElement("minimum"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uintptr_t minimum
     * }
     */
    public static final long minimum$offset() {
        return minimum$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uintptr_t minimum
     * }
     */
    public static long minimum(MemorySegment struct) {
        return struct.get(minimum$LAYOUT, minimum$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uintptr_t minimum
     * }
     */
    public static void minimum(MemorySegment struct, long fieldValue) {
        struct.set(minimum$LAYOUT, minimum$OFFSET, fieldValue);
    }

    private static final OfLong maximum$LAYOUT = (OfLong)$LAYOUT.select(groupElement("maximum"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uintptr_t maximum
     * }
     */
    public static final OfLong maximum$layout() {
        return maximum$LAYOUT;
    }

    private static final long maximum$OFFSET = $LAYOUT.byteOffset(groupElement("maximum"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uintptr_t maximum
     * }
     */
    public static final long maximum$offset() {
        return maximum$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uintptr_t maximum
     * }
     */
    public static long maximum(MemorySegment struct) {
        return struct.get(maximum$LAYOUT, maximum$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uintptr_t maximum
     * }
     */
    public static void maximum(MemorySegment struct, long fieldValue) {
        struct.set(maximum$LAYOUT, maximum$OFFSET, fieldValue);
    }

    private static final OfLong initial$LAYOUT = (OfLong)$LAYOUT.select(groupElement("initial"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uintptr_t initial
     * }
     */
    public static final OfLong initial$layout() {
        return initial$LAYOUT;
    }

    private static final long initial$OFFSET = $LAYOUT.byteOffset(groupElement("initial"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uintptr_t initial
     * }
     */
    public static final long initial$offset() {
        return initial$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uintptr_t initial
     * }
     */
    public static long initial(MemorySegment struct) {
        return struct.get(initial$LAYOUT, initial$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uintptr_t initial
     * }
     */
    public static void initial(MemorySegment struct, long fieldValue) {
        struct.set(initial$LAYOUT, initial$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

