// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*TemporalCoreClientRpcCallCallback)(void *, const struct TemporalCoreByteArray {
 *     const uint8_t *data;
 *     size_t size;
 *     size_t cap;
 *     bool disable_free;
 * } *, uint32_t, const struct TemporalCoreByteArray {
 *     const uint8_t *data;
 *     size_t size;
 *     size_t cap;
 *     bool disable_free;
 * } *, const struct TemporalCoreByteArray {
 *     const uint8_t *data;
 *     size_t size;
 *     size_t cap;
 *     bool disable_free;
 * } *)
 * }
 */
public final class TemporalCoreClientRpcCallCallback {

    private TemporalCoreClientRpcCallCallback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment user_data, MemorySegment success, int status_code, MemorySegment failure_message, MemorySegment failure_details);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        temporal_sdk_core_c_bridge_h.C_POINTER,
        temporal_sdk_core_c_bridge_h.C_POINTER,
        temporal_sdk_core_c_bridge_h.C_INT,
        temporal_sdk_core_c_bridge_h.C_POINTER,
        temporal_sdk_core_c_bridge_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = temporal_sdk_core_c_bridge_h.upcallHandle(TemporalCoreClientRpcCallCallback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(TemporalCoreClientRpcCallCallback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, MemorySegment user_data, MemorySegment success, int status_code, MemorySegment failure_message, MemorySegment failure_details) {
        try {
             DOWN$MH.invokeExact(funcPtr, user_data, success, status_code, failure_message, failure_details);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

