// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreWorkerDeploymentVersion {
 *     struct TemporalCoreByteArrayRef deployment_name;
 *     struct TemporalCoreByteArrayRef build_id;
 * }
 * }
 */
public class TemporalCoreWorkerDeploymentVersion {

    TemporalCoreWorkerDeploymentVersion() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TemporalCoreByteArrayRef.layout().withName("deployment_name"),
        TemporalCoreByteArrayRef.layout().withName("build_id")
    ).withName("TemporalCoreWorkerDeploymentVersion");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout deployment_name$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("deployment_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef deployment_name
     * }
     */
    public static final GroupLayout deployment_name$layout() {
        return deployment_name$LAYOUT;
    }

    private static final long deployment_name$OFFSET = $LAYOUT.byteOffset(groupElement("deployment_name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef deployment_name
     * }
     */
    public static final long deployment_name$offset() {
        return deployment_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef deployment_name
     * }
     */
    public static MemorySegment deployment_name(MemorySegment struct) {
        return struct.asSlice(deployment_name$OFFSET, deployment_name$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef deployment_name
     * }
     */
    public static void deployment_name(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, deployment_name$OFFSET, deployment_name$LAYOUT.byteSize());
    }

    private static final GroupLayout build_id$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("build_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef build_id
     * }
     */
    public static final GroupLayout build_id$layout() {
        return build_id$LAYOUT;
    }

    private static final long build_id$OFFSET = $LAYOUT.byteOffset(groupElement("build_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef build_id
     * }
     */
    public static final long build_id$offset() {
        return build_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef build_id
     * }
     */
    public static MemorySegment build_id(MemorySegment struct) {
        return struct.asSlice(build_id$OFFSET, build_id$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef build_id
     * }
     */
    public static void build_id(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, build_id$OFFSET, build_id$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

