// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreClientEnvConfigProfileLoadOptions {
 *     struct TemporalCoreByteArrayRef profile;
 *     struct TemporalCoreByteArrayRef path;
 *     struct TemporalCoreByteArrayRef data;
 *     bool disable_file;
 *     bool disable_env;
 *     bool config_file_strict;
 *     struct TemporalCoreByteArrayRef env_vars;
 * }
 * }
 */
public class TemporalCoreClientEnvConfigProfileLoadOptions {

    TemporalCoreClientEnvConfigProfileLoadOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TemporalCoreByteArrayRef.layout().withName("profile"),
        TemporalCoreByteArrayRef.layout().withName("path"),
        TemporalCoreByteArrayRef.layout().withName("data"),
        temporal_sdk_core_c_bridge_h.C_BOOL.withName("disable_file"),
        temporal_sdk_core_c_bridge_h.C_BOOL.withName("disable_env"),
        temporal_sdk_core_c_bridge_h.C_BOOL.withName("config_file_strict"),
        MemoryLayout.paddingLayout(5),
        TemporalCoreByteArrayRef.layout().withName("env_vars")
    ).withName("TemporalCoreClientEnvConfigProfileLoadOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout profile$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("profile"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef profile
     * }
     */
    public static final GroupLayout profile$layout() {
        return profile$LAYOUT;
    }

    private static final long profile$OFFSET = $LAYOUT.byteOffset(groupElement("profile"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef profile
     * }
     */
    public static final long profile$offset() {
        return profile$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef profile
     * }
     */
    public static MemorySegment profile(MemorySegment struct) {
        return struct.asSlice(profile$OFFSET, profile$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef profile
     * }
     */
    public static void profile(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, profile$OFFSET, profile$LAYOUT.byteSize());
    }

    private static final GroupLayout path$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("path"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef path
     * }
     */
    public static final GroupLayout path$layout() {
        return path$LAYOUT;
    }

    private static final long path$OFFSET = $LAYOUT.byteOffset(groupElement("path"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef path
     * }
     */
    public static final long path$offset() {
        return path$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef path
     * }
     */
    public static MemorySegment path(MemorySegment struct) {
        return struct.asSlice(path$OFFSET, path$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef path
     * }
     */
    public static void path(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, path$OFFSET, path$LAYOUT.byteSize());
    }

    private static final GroupLayout data$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef data
     * }
     */
    public static final GroupLayout data$layout() {
        return data$LAYOUT;
    }

    private static final long data$OFFSET = $LAYOUT.byteOffset(groupElement("data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef data
     * }
     */
    public static final long data$offset() {
        return data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef data
     * }
     */
    public static MemorySegment data(MemorySegment struct) {
        return struct.asSlice(data$OFFSET, data$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef data
     * }
     */
    public static void data(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, data$OFFSET, data$LAYOUT.byteSize());
    }

    private static final OfBoolean disable_file$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("disable_file"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool disable_file
     * }
     */
    public static final OfBoolean disable_file$layout() {
        return disable_file$LAYOUT;
    }

    private static final long disable_file$OFFSET = $LAYOUT.byteOffset(groupElement("disable_file"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool disable_file
     * }
     */
    public static final long disable_file$offset() {
        return disable_file$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool disable_file
     * }
     */
    public static boolean disable_file(MemorySegment struct) {
        return struct.get(disable_file$LAYOUT, disable_file$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool disable_file
     * }
     */
    public static void disable_file(MemorySegment struct, boolean fieldValue) {
        struct.set(disable_file$LAYOUT, disable_file$OFFSET, fieldValue);
    }

    private static final OfBoolean disable_env$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("disable_env"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool disable_env
     * }
     */
    public static final OfBoolean disable_env$layout() {
        return disable_env$LAYOUT;
    }

    private static final long disable_env$OFFSET = $LAYOUT.byteOffset(groupElement("disable_env"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool disable_env
     * }
     */
    public static final long disable_env$offset() {
        return disable_env$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool disable_env
     * }
     */
    public static boolean disable_env(MemorySegment struct) {
        return struct.get(disable_env$LAYOUT, disable_env$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool disable_env
     * }
     */
    public static void disable_env(MemorySegment struct, boolean fieldValue) {
        struct.set(disable_env$LAYOUT, disable_env$OFFSET, fieldValue);
    }

    private static final OfBoolean config_file_strict$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("config_file_strict"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool config_file_strict
     * }
     */
    public static final OfBoolean config_file_strict$layout() {
        return config_file_strict$LAYOUT;
    }

    private static final long config_file_strict$OFFSET = $LAYOUT.byteOffset(groupElement("config_file_strict"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool config_file_strict
     * }
     */
    public static final long config_file_strict$offset() {
        return config_file_strict$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool config_file_strict
     * }
     */
    public static boolean config_file_strict(MemorySegment struct) {
        return struct.get(config_file_strict$LAYOUT, config_file_strict$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool config_file_strict
     * }
     */
    public static void config_file_strict(MemorySegment struct, boolean fieldValue) {
        struct.set(config_file_strict$LAYOUT, config_file_strict$OFFSET, fieldValue);
    }

    private static final GroupLayout env_vars$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("env_vars"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef env_vars
     * }
     */
    public static final GroupLayout env_vars$layout() {
        return env_vars$LAYOUT;
    }

    private static final long env_vars$OFFSET = $LAYOUT.byteOffset(groupElement("env_vars"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef env_vars
     * }
     */
    public static final long env_vars$offset() {
        return env_vars$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef env_vars
     * }
     */
    public static MemorySegment env_vars(MemorySegment struct) {
        return struct.asSlice(env_vars$OFFSET, env_vars$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef env_vars
     * }
     */
    public static void env_vars(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, env_vars$OFFSET, env_vars$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

