// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef const void *(*TemporalCoreCustomMetricMeterAttributesNewCallback)(const void *, const struct TemporalCoreCustomMetricAttribute {
 *     struct TemporalCoreByteArrayRef key;
 *     union TemporalCoreCustomMetricAttributeValue value;
 *     enum TemporalCoreMetricAttributeValueType value_type;
 * } *, size_t)
 * }
 */
public final class TemporalCoreCustomMetricMeterAttributesNewCallback {

    private TemporalCoreCustomMetricMeterAttributesNewCallback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        MemorySegment apply(MemorySegment append_from, MemorySegment attributes, long attributes_size);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        temporal_sdk_core_c_bridge_h.C_POINTER,
        temporal_sdk_core_c_bridge_h.C_POINTER,
        temporal_sdk_core_c_bridge_h.C_POINTER,
        temporal_sdk_core_c_bridge_h.C_LONG
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = temporal_sdk_core_c_bridge_h.upcallHandle(TemporalCoreCustomMetricMeterAttributesNewCallback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(TemporalCoreCustomMetricMeterAttributesNewCallback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment append_from, MemorySegment attributes, long attributes_size) {
        try {
            return (MemorySegment) DOWN$MH.invokeExact(funcPtr, append_from, attributes, attributes_size);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

