// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreTestServerOptions {
 *     struct TemporalCoreByteArrayRef existing_path;
 *     struct TemporalCoreByteArrayRef sdk_name;
 *     struct TemporalCoreByteArrayRef sdk_version;
 *     struct TemporalCoreByteArrayRef download_version;
 *     struct TemporalCoreByteArrayRef download_dest_dir;
 *     uint16_t port;
 *     struct TemporalCoreByteArrayRef extra_args;
 *     uint64_t download_ttl_seconds;
 * }
 * }
 */
public class TemporalCoreTestServerOptions {

    TemporalCoreTestServerOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TemporalCoreByteArrayRef.layout().withName("existing_path"),
        TemporalCoreByteArrayRef.layout().withName("sdk_name"),
        TemporalCoreByteArrayRef.layout().withName("sdk_version"),
        TemporalCoreByteArrayRef.layout().withName("download_version"),
        TemporalCoreByteArrayRef.layout().withName("download_dest_dir"),
        temporal_sdk_core_c_bridge_h.C_SHORT.withName("port"),
        MemoryLayout.paddingLayout(6),
        TemporalCoreByteArrayRef.layout().withName("extra_args"),
        temporal_sdk_core_c_bridge_h.C_LONG_LONG.withName("download_ttl_seconds")
    ).withName("TemporalCoreTestServerOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout existing_path$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("existing_path"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef existing_path
     * }
     */
    public static final GroupLayout existing_path$layout() {
        return existing_path$LAYOUT;
    }

    private static final long existing_path$OFFSET = $LAYOUT.byteOffset(groupElement("existing_path"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef existing_path
     * }
     */
    public static final long existing_path$offset() {
        return existing_path$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef existing_path
     * }
     */
    public static MemorySegment existing_path(MemorySegment struct) {
        return struct.asSlice(existing_path$OFFSET, existing_path$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef existing_path
     * }
     */
    public static void existing_path(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, existing_path$OFFSET, existing_path$LAYOUT.byteSize());
    }

    private static final GroupLayout sdk_name$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("sdk_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef sdk_name
     * }
     */
    public static final GroupLayout sdk_name$layout() {
        return sdk_name$LAYOUT;
    }

    private static final long sdk_name$OFFSET = $LAYOUT.byteOffset(groupElement("sdk_name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef sdk_name
     * }
     */
    public static final long sdk_name$offset() {
        return sdk_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef sdk_name
     * }
     */
    public static MemorySegment sdk_name(MemorySegment struct) {
        return struct.asSlice(sdk_name$OFFSET, sdk_name$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef sdk_name
     * }
     */
    public static void sdk_name(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, sdk_name$OFFSET, sdk_name$LAYOUT.byteSize());
    }

    private static final GroupLayout sdk_version$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("sdk_version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef sdk_version
     * }
     */
    public static final GroupLayout sdk_version$layout() {
        return sdk_version$LAYOUT;
    }

    private static final long sdk_version$OFFSET = $LAYOUT.byteOffset(groupElement("sdk_version"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef sdk_version
     * }
     */
    public static final long sdk_version$offset() {
        return sdk_version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef sdk_version
     * }
     */
    public static MemorySegment sdk_version(MemorySegment struct) {
        return struct.asSlice(sdk_version$OFFSET, sdk_version$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef sdk_version
     * }
     */
    public static void sdk_version(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, sdk_version$OFFSET, sdk_version$LAYOUT.byteSize());
    }

    private static final GroupLayout download_version$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("download_version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef download_version
     * }
     */
    public static final GroupLayout download_version$layout() {
        return download_version$LAYOUT;
    }

    private static final long download_version$OFFSET = $LAYOUT.byteOffset(groupElement("download_version"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef download_version
     * }
     */
    public static final long download_version$offset() {
        return download_version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef download_version
     * }
     */
    public static MemorySegment download_version(MemorySegment struct) {
        return struct.asSlice(download_version$OFFSET, download_version$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef download_version
     * }
     */
    public static void download_version(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, download_version$OFFSET, download_version$LAYOUT.byteSize());
    }

    private static final GroupLayout download_dest_dir$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("download_dest_dir"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef download_dest_dir
     * }
     */
    public static final GroupLayout download_dest_dir$layout() {
        return download_dest_dir$LAYOUT;
    }

    private static final long download_dest_dir$OFFSET = $LAYOUT.byteOffset(groupElement("download_dest_dir"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef download_dest_dir
     * }
     */
    public static final long download_dest_dir$offset() {
        return download_dest_dir$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef download_dest_dir
     * }
     */
    public static MemorySegment download_dest_dir(MemorySegment struct) {
        return struct.asSlice(download_dest_dir$OFFSET, download_dest_dir$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef download_dest_dir
     * }
     */
    public static void download_dest_dir(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, download_dest_dir$OFFSET, download_dest_dir$LAYOUT.byteSize());
    }

    private static final OfShort port$LAYOUT = (OfShort)$LAYOUT.select(groupElement("port"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t port
     * }
     */
    public static final OfShort port$layout() {
        return port$LAYOUT;
    }

    private static final long port$OFFSET = $LAYOUT.byteOffset(groupElement("port"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t port
     * }
     */
    public static final long port$offset() {
        return port$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t port
     * }
     */
    public static short port(MemorySegment struct) {
        return struct.get(port$LAYOUT, port$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t port
     * }
     */
    public static void port(MemorySegment struct, short fieldValue) {
        struct.set(port$LAYOUT, port$OFFSET, fieldValue);
    }

    private static final GroupLayout extra_args$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("extra_args"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef extra_args
     * }
     */
    public static final GroupLayout extra_args$layout() {
        return extra_args$LAYOUT;
    }

    private static final long extra_args$OFFSET = $LAYOUT.byteOffset(groupElement("extra_args"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef extra_args
     * }
     */
    public static final long extra_args$offset() {
        return extra_args$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef extra_args
     * }
     */
    public static MemorySegment extra_args(MemorySegment struct) {
        return struct.asSlice(extra_args$OFFSET, extra_args$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef extra_args
     * }
     */
    public static void extra_args(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, extra_args$OFFSET, extra_args$LAYOUT.byteSize());
    }

    private static final OfLong download_ttl_seconds$LAYOUT = (OfLong)$LAYOUT.select(groupElement("download_ttl_seconds"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t download_ttl_seconds
     * }
     */
    public static final OfLong download_ttl_seconds$layout() {
        return download_ttl_seconds$LAYOUT;
    }

    private static final long download_ttl_seconds$OFFSET = $LAYOUT.byteOffset(groupElement("download_ttl_seconds"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t download_ttl_seconds
     * }
     */
    public static final long download_ttl_seconds$offset() {
        return download_ttl_seconds$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t download_ttl_seconds
     * }
     */
    public static long download_ttl_seconds(MemorySegment struct) {
        return struct.get(download_ttl_seconds$LAYOUT, download_ttl_seconds$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t download_ttl_seconds
     * }
     */
    public static void download_ttl_seconds(MemorySegment struct, long fieldValue) {
        struct.set(download_ttl_seconds$LAYOUT, download_ttl_seconds$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

