// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreWorkflowSlotInfo_Body {
 *     struct TemporalCoreByteArrayRef workflow_type;
 *     bool is_sticky;
 * }
 * }
 */
public class TemporalCoreWorkflowSlotInfo_Body {

    TemporalCoreWorkflowSlotInfo_Body() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TemporalCoreByteArrayRef.layout().withName("workflow_type"),
        temporal_sdk_core_c_bridge_h.C_BOOL.withName("is_sticky"),
        MemoryLayout.paddingLayout(7)
    ).withName("TemporalCoreWorkflowSlotInfo_Body");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout workflow_type$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("workflow_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef workflow_type
     * }
     */
    public static final GroupLayout workflow_type$layout() {
        return workflow_type$LAYOUT;
    }

    private static final long workflow_type$OFFSET = $LAYOUT.byteOffset(groupElement("workflow_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef workflow_type
     * }
     */
    public static final long workflow_type$offset() {
        return workflow_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef workflow_type
     * }
     */
    public static MemorySegment workflow_type(MemorySegment struct) {
        return struct.asSlice(workflow_type$OFFSET, workflow_type$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef workflow_type
     * }
     */
    public static void workflow_type(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, workflow_type$OFFSET, workflow_type$LAYOUT.byteSize());
    }

    private static final OfBoolean is_sticky$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("is_sticky"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool is_sticky
     * }
     */
    public static final OfBoolean is_sticky$layout() {
        return is_sticky$LAYOUT;
    }

    private static final long is_sticky$OFFSET = $LAYOUT.byteOffset(groupElement("is_sticky"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool is_sticky
     * }
     */
    public static final long is_sticky$offset() {
        return is_sticky$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool is_sticky
     * }
     */
    public static boolean is_sticky(MemorySegment struct) {
        return struct.get(is_sticky$LAYOUT, is_sticky$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool is_sticky
     * }
     */
    public static void is_sticky(MemorySegment struct, boolean fieldValue) {
        struct.set(is_sticky$LAYOUT, is_sticky$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

