// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreResourceBasedTunerOptions {
 *     double target_memory_usage;
 *     double target_cpu_usage;
 * }
 * }
 */
public class TemporalCoreResourceBasedTunerOptions {

    TemporalCoreResourceBasedTunerOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_DOUBLE.withName("target_memory_usage"),
        temporal_sdk_core_c_bridge_h.C_DOUBLE.withName("target_cpu_usage")
    ).withName("TemporalCoreResourceBasedTunerOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfDouble target_memory_usage$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("target_memory_usage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double target_memory_usage
     * }
     */
    public static final OfDouble target_memory_usage$layout() {
        return target_memory_usage$LAYOUT;
    }

    private static final long target_memory_usage$OFFSET = $LAYOUT.byteOffset(groupElement("target_memory_usage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double target_memory_usage
     * }
     */
    public static final long target_memory_usage$offset() {
        return target_memory_usage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double target_memory_usage
     * }
     */
    public static double target_memory_usage(MemorySegment struct) {
        return struct.get(target_memory_usage$LAYOUT, target_memory_usage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double target_memory_usage
     * }
     */
    public static void target_memory_usage(MemorySegment struct, double fieldValue) {
        struct.set(target_memory_usage$LAYOUT, target_memory_usage$OFFSET, fieldValue);
    }

    private static final OfDouble target_cpu_usage$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("target_cpu_usage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double target_cpu_usage
     * }
     */
    public static final OfDouble target_cpu_usage$layout() {
        return target_cpu_usage$LAYOUT;
    }

    private static final long target_cpu_usage$OFFSET = $LAYOUT.byteOffset(groupElement("target_cpu_usage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double target_cpu_usage
     * }
     */
    public static final long target_cpu_usage$offset() {
        return target_cpu_usage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double target_cpu_usage
     * }
     */
    public static double target_cpu_usage(MemorySegment struct) {
        return struct.get(target_cpu_usage$LAYOUT, target_cpu_usage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double target_cpu_usage
     * }
     */
    public static void target_cpu_usage(MemorySegment struct, double fieldValue) {
        struct.set(target_cpu_usage$LAYOUT, target_cpu_usage$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

