// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreClientGrpcOverrideResponse {
 *     int32_t status_code;
 *     TemporalCoreMetadataRef headers;
 *     struct TemporalCoreByteArrayRef success_proto;
 *     struct TemporalCoreByteArrayRef fail_message;
 *     struct TemporalCoreByteArrayRef fail_details;
 * }
 * }
 */
public class TemporalCoreClientGrpcOverrideResponse {

    TemporalCoreClientGrpcOverrideResponse() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_INT.withName("status_code"),
        MemoryLayout.paddingLayout(4),
        TemporalCoreByteArrayRefArray.layout().withName("headers"),
        TemporalCoreByteArrayRef.layout().withName("success_proto"),
        TemporalCoreByteArrayRef.layout().withName("fail_message"),
        TemporalCoreByteArrayRef.layout().withName("fail_details")
    ).withName("TemporalCoreClientGrpcOverrideResponse");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt status_code$LAYOUT = (OfInt)$LAYOUT.select(groupElement("status_code"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t status_code
     * }
     */
    public static final OfInt status_code$layout() {
        return status_code$LAYOUT;
    }

    private static final long status_code$OFFSET = $LAYOUT.byteOffset(groupElement("status_code"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t status_code
     * }
     */
    public static final long status_code$offset() {
        return status_code$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t status_code
     * }
     */
    public static int status_code(MemorySegment struct) {
        return struct.get(status_code$LAYOUT, status_code$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t status_code
     * }
     */
    public static void status_code(MemorySegment struct, int fieldValue) {
        struct.set(status_code$LAYOUT, status_code$OFFSET, fieldValue);
    }

    private static final GroupLayout headers$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("headers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreMetadataRef headers
     * }
     */
    public static final GroupLayout headers$layout() {
        return headers$LAYOUT;
    }

    private static final long headers$OFFSET = $LAYOUT.byteOffset(groupElement("headers"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreMetadataRef headers
     * }
     */
    public static final long headers$offset() {
        return headers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreMetadataRef headers
     * }
     */
    public static MemorySegment headers(MemorySegment struct) {
        return struct.asSlice(headers$OFFSET, headers$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreMetadataRef headers
     * }
     */
    public static void headers(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, headers$OFFSET, headers$LAYOUT.byteSize());
    }

    private static final GroupLayout success_proto$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("success_proto"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef success_proto
     * }
     */
    public static final GroupLayout success_proto$layout() {
        return success_proto$LAYOUT;
    }

    private static final long success_proto$OFFSET = $LAYOUT.byteOffset(groupElement("success_proto"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef success_proto
     * }
     */
    public static final long success_proto$offset() {
        return success_proto$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef success_proto
     * }
     */
    public static MemorySegment success_proto(MemorySegment struct) {
        return struct.asSlice(success_proto$OFFSET, success_proto$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef success_proto
     * }
     */
    public static void success_proto(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, success_proto$OFFSET, success_proto$LAYOUT.byteSize());
    }

    private static final GroupLayout fail_message$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("fail_message"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef fail_message
     * }
     */
    public static final GroupLayout fail_message$layout() {
        return fail_message$LAYOUT;
    }

    private static final long fail_message$OFFSET = $LAYOUT.byteOffset(groupElement("fail_message"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef fail_message
     * }
     */
    public static final long fail_message$offset() {
        return fail_message$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef fail_message
     * }
     */
    public static MemorySegment fail_message(MemorySegment struct) {
        return struct.asSlice(fail_message$OFFSET, fail_message$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef fail_message
     * }
     */
    public static void fail_message(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, fail_message$OFFSET, fail_message$LAYOUT.byteSize());
    }

    private static final GroupLayout fail_details$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("fail_details"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef fail_details
     * }
     */
    public static final GroupLayout fail_details$layout() {
        return fail_details$LAYOUT;
    }

    private static final long fail_details$OFFSET = $LAYOUT.byteOffset(groupElement("fail_details"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef fail_details
     * }
     */
    public static final long fail_details$offset() {
        return fail_details$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef fail_details
     * }
     */
    public static MemorySegment fail_details(MemorySegment struct) {
        return struct.asSlice(fail_details$OFFSET, fail_details$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef fail_details
     * }
     */
    public static void fail_details(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, fail_details$OFFSET, fail_details$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

