// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct TemporalCoreByteArrayRefArray {
 *     const struct TemporalCoreByteArrayRef *data;
 *     size_t size;
 * } TemporalCoreMetadataRef
 * }
 */
public class TemporalCoreMetadataRef extends TemporalCoreByteArrayRefArray {

    TemporalCoreMetadataRef() {
        // Should not be called directly
    }
}

