// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreCustomMetricMeter {
 *     TemporalCoreCustomMetricMeterMetricNewCallback metric_new;
 *     TemporalCoreCustomMetricMeterMetricFreeCallback metric_free;
 *     TemporalCoreCustomMetricMeterMetricRecordIntegerCallback metric_record_integer;
 *     TemporalCoreCustomMetricMeterMetricRecordFloatCallback metric_record_float;
 *     TemporalCoreCustomMetricMeterMetricRecordDurationCallback metric_record_duration;
 *     TemporalCoreCustomMetricMeterAttributesNewCallback attributes_new;
 *     TemporalCoreCustomMetricMeterAttributesFreeCallback attributes_free;
 *     TemporalCoreCustomMetricMeterMeterFreeCallback meter_free;
 * }
 * }
 */
public class TemporalCoreCustomMetricMeter$0 {

    TemporalCoreCustomMetricMeter$0() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("metric_new"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("metric_free"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("metric_record_integer"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("metric_record_float"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("metric_record_duration"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("attributes_new"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("attributes_free"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("meter_free")
    ).withName("TemporalCoreCustomMetricMeter");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout metric_new$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("metric_new"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricNewCallback metric_new
     * }
     */
    public static final AddressLayout metric_new$layout() {
        return metric_new$LAYOUT;
    }

    private static final long metric_new$OFFSET = $LAYOUT.byteOffset(groupElement("metric_new"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricNewCallback metric_new
     * }
     */
    public static final long metric_new$offset() {
        return metric_new$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricNewCallback metric_new
     * }
     */
    public static MemorySegment metric_new(MemorySegment struct) {
        return struct.get(metric_new$LAYOUT, metric_new$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricNewCallback metric_new
     * }
     */
    public static void metric_new(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(metric_new$LAYOUT, metric_new$OFFSET, fieldValue);
    }

    private static final AddressLayout metric_free$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("metric_free"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricFreeCallback metric_free
     * }
     */
    public static final AddressLayout metric_free$layout() {
        return metric_free$LAYOUT;
    }

    private static final long metric_free$OFFSET = $LAYOUT.byteOffset(groupElement("metric_free"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricFreeCallback metric_free
     * }
     */
    public static final long metric_free$offset() {
        return metric_free$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricFreeCallback metric_free
     * }
     */
    public static MemorySegment metric_free(MemorySegment struct) {
        return struct.get(metric_free$LAYOUT, metric_free$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricFreeCallback metric_free
     * }
     */
    public static void metric_free(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(metric_free$LAYOUT, metric_free$OFFSET, fieldValue);
    }

    private static final AddressLayout metric_record_integer$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("metric_record_integer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricRecordIntegerCallback metric_record_integer
     * }
     */
    public static final AddressLayout metric_record_integer$layout() {
        return metric_record_integer$LAYOUT;
    }

    private static final long metric_record_integer$OFFSET = $LAYOUT.byteOffset(groupElement("metric_record_integer"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricRecordIntegerCallback metric_record_integer
     * }
     */
    public static final long metric_record_integer$offset() {
        return metric_record_integer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricRecordIntegerCallback metric_record_integer
     * }
     */
    public static MemorySegment metric_record_integer(MemorySegment struct) {
        return struct.get(metric_record_integer$LAYOUT, metric_record_integer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricRecordIntegerCallback metric_record_integer
     * }
     */
    public static void metric_record_integer(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(metric_record_integer$LAYOUT, metric_record_integer$OFFSET, fieldValue);
    }

    private static final AddressLayout metric_record_float$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("metric_record_float"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricRecordFloatCallback metric_record_float
     * }
     */
    public static final AddressLayout metric_record_float$layout() {
        return metric_record_float$LAYOUT;
    }

    private static final long metric_record_float$OFFSET = $LAYOUT.byteOffset(groupElement("metric_record_float"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricRecordFloatCallback metric_record_float
     * }
     */
    public static final long metric_record_float$offset() {
        return metric_record_float$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricRecordFloatCallback metric_record_float
     * }
     */
    public static MemorySegment metric_record_float(MemorySegment struct) {
        return struct.get(metric_record_float$LAYOUT, metric_record_float$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricRecordFloatCallback metric_record_float
     * }
     */
    public static void metric_record_float(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(metric_record_float$LAYOUT, metric_record_float$OFFSET, fieldValue);
    }

    private static final AddressLayout metric_record_duration$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("metric_record_duration"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricRecordDurationCallback metric_record_duration
     * }
     */
    public static final AddressLayout metric_record_duration$layout() {
        return metric_record_duration$LAYOUT;
    }

    private static final long metric_record_duration$OFFSET = $LAYOUT.byteOffset(groupElement("metric_record_duration"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricRecordDurationCallback metric_record_duration
     * }
     */
    public static final long metric_record_duration$offset() {
        return metric_record_duration$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricRecordDurationCallback metric_record_duration
     * }
     */
    public static MemorySegment metric_record_duration(MemorySegment struct) {
        return struct.get(metric_record_duration$LAYOUT, metric_record_duration$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMetricRecordDurationCallback metric_record_duration
     * }
     */
    public static void metric_record_duration(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(metric_record_duration$LAYOUT, metric_record_duration$OFFSET, fieldValue);
    }

    private static final AddressLayout attributes_new$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("attributes_new"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterAttributesNewCallback attributes_new
     * }
     */
    public static final AddressLayout attributes_new$layout() {
        return attributes_new$LAYOUT;
    }

    private static final long attributes_new$OFFSET = $LAYOUT.byteOffset(groupElement("attributes_new"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterAttributesNewCallback attributes_new
     * }
     */
    public static final long attributes_new$offset() {
        return attributes_new$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterAttributesNewCallback attributes_new
     * }
     */
    public static MemorySegment attributes_new(MemorySegment struct) {
        return struct.get(attributes_new$LAYOUT, attributes_new$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterAttributesNewCallback attributes_new
     * }
     */
    public static void attributes_new(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(attributes_new$LAYOUT, attributes_new$OFFSET, fieldValue);
    }

    private static final AddressLayout attributes_free$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("attributes_free"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterAttributesFreeCallback attributes_free
     * }
     */
    public static final AddressLayout attributes_free$layout() {
        return attributes_free$LAYOUT;
    }

    private static final long attributes_free$OFFSET = $LAYOUT.byteOffset(groupElement("attributes_free"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterAttributesFreeCallback attributes_free
     * }
     */
    public static final long attributes_free$offset() {
        return attributes_free$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterAttributesFreeCallback attributes_free
     * }
     */
    public static MemorySegment attributes_free(MemorySegment struct) {
        return struct.get(attributes_free$LAYOUT, attributes_free$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterAttributesFreeCallback attributes_free
     * }
     */
    public static void attributes_free(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(attributes_free$LAYOUT, attributes_free$OFFSET, fieldValue);
    }

    private static final AddressLayout meter_free$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("meter_free"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMeterFreeCallback meter_free
     * }
     */
    public static final AddressLayout meter_free$layout() {
        return meter_free$LAYOUT;
    }

    private static final long meter_free$OFFSET = $LAYOUT.byteOffset(groupElement("meter_free"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMeterFreeCallback meter_free
     * }
     */
    public static final long meter_free$offset() {
        return meter_free$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMeterFreeCallback meter_free
     * }
     */
    public static MemorySegment meter_free(MemorySegment struct) {
        return struct.get(meter_free$LAYOUT, meter_free$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomMetricMeterMeterFreeCallback meter_free
     * }
     */
    public static void meter_free(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(meter_free$LAYOUT, meter_free$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

