// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreWorkerOrFail {
 *     struct TemporalCoreWorker *worker;
 *     const struct TemporalCoreByteArray *fail;
 * }
 * }
 */
public class TemporalCoreWorkerOrFail {

    TemporalCoreWorkerOrFail() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("worker"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("fail")
    ).withName("TemporalCoreWorkerOrFail");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout worker$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("worker"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreWorker *worker
     * }
     */
    public static final AddressLayout worker$layout() {
        return worker$LAYOUT;
    }

    private static final long worker$OFFSET = $LAYOUT.byteOffset(groupElement("worker"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreWorker *worker
     * }
     */
    public static final long worker$offset() {
        return worker$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreWorker *worker
     * }
     */
    public static MemorySegment worker(MemorySegment struct) {
        return struct.get(worker$LAYOUT, worker$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreWorker *worker
     * }
     */
    public static void worker(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(worker$LAYOUT, worker$OFFSET, fieldValue);
    }

    private static final AddressLayout fail$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("fail"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct TemporalCoreByteArray *fail
     * }
     */
    public static final AddressLayout fail$layout() {
        return fail$LAYOUT;
    }

    private static final long fail$OFFSET = $LAYOUT.byteOffset(groupElement("fail"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct TemporalCoreByteArray *fail
     * }
     */
    public static final long fail$offset() {
        return fail$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreByteArray *fail
     * }
     */
    public static MemorySegment fail(MemorySegment struct) {
        return struct.get(fail$LAYOUT, fail$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreByteArray *fail
     * }
     */
    public static void fail(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(fail$LAYOUT, fail$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

