// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreRuntimeInfo {
 *     enum TemporalCoreRuntimeType runtime_type;
 *     struct TemporalCoreByteArrayRef version;
 * }
 * }
 */
public class TemporalCoreRuntimeInfo {

    TemporalCoreRuntimeInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_INT.withName("runtime_type"),
        MemoryLayout.paddingLayout(4),
        TemporalCoreByteArrayRef.layout().withName("version")
    ).withName("TemporalCoreRuntimeInfo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt runtime_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("runtime_type"));
    private static final long runtime_type$OFFSET = $LAYOUT.byteOffset(groupElement("runtime_type"));

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum TemporalCoreRuntimeType runtime_type
     * }
     */
    public static int runtime_type(MemorySegment struct) {
        return struct.get(runtime_type$LAYOUT, runtime_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum TemporalCoreRuntimeType runtime_type
     * }
     */
    public static void runtime_type(MemorySegment struct, int fieldValue) {
        struct.set(runtime_type$LAYOUT, runtime_type$OFFSET, fieldValue);
    }

    private static final GroupLayout version$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("version"));
    private static final long version$OFFSET = $LAYOUT.byteOffset(groupElement("version"));

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef version
     * }
     */
    public static MemorySegment version(MemorySegment struct) {
        return struct.asSlice(version$OFFSET, version$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef version
     * }
     */
    public static void version(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, version$OFFSET, version$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}
