// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreSlotReserveCtx {
 *     enum TemporalCoreSlotKindType slot_type;
 *     struct TemporalCoreByteArrayRef task_queue;
 *     struct TemporalCoreByteArrayRef worker_identity;
 *     struct TemporalCoreByteArrayRef worker_build_id;
 *     bool is_sticky;
 * }
 * }
 */
public class TemporalCoreSlotReserveCtx {

    TemporalCoreSlotReserveCtx() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_INT.withName("slot_type"),
        MemoryLayout.paddingLayout(4),
        TemporalCoreByteArrayRef.layout().withName("task_queue"),
        TemporalCoreByteArrayRef.layout().withName("worker_identity"),
        TemporalCoreByteArrayRef.layout().withName("worker_build_id"),
        temporal_sdk_core_c_bridge_h.C_BOOL.withName("is_sticky"),
        MemoryLayout.paddingLayout(7)
    ).withName("TemporalCoreSlotReserveCtx");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt slot_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("slot_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum TemporalCoreSlotKindType slot_type
     * }
     */
    public static final OfInt slot_type$layout() {
        return slot_type$LAYOUT;
    }

    private static final long slot_type$OFFSET = $LAYOUT.byteOffset(groupElement("slot_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum TemporalCoreSlotKindType slot_type
     * }
     */
    public static final long slot_type$offset() {
        return slot_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum TemporalCoreSlotKindType slot_type
     * }
     */
    public static int slot_type(MemorySegment struct) {
        return struct.get(slot_type$LAYOUT, slot_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum TemporalCoreSlotKindType slot_type
     * }
     */
    public static void slot_type(MemorySegment struct, int fieldValue) {
        struct.set(slot_type$LAYOUT, slot_type$OFFSET, fieldValue);
    }

    private static final GroupLayout task_queue$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("task_queue"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef task_queue
     * }
     */
    public static final GroupLayout task_queue$layout() {
        return task_queue$LAYOUT;
    }

    private static final long task_queue$OFFSET = $LAYOUT.byteOffset(groupElement("task_queue"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef task_queue
     * }
     */
    public static final long task_queue$offset() {
        return task_queue$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef task_queue
     * }
     */
    public static MemorySegment task_queue(MemorySegment struct) {
        return struct.asSlice(task_queue$OFFSET, task_queue$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef task_queue
     * }
     */
    public static void task_queue(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, task_queue$OFFSET, task_queue$LAYOUT.byteSize());
    }

    private static final GroupLayout worker_identity$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("worker_identity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef worker_identity
     * }
     */
    public static final GroupLayout worker_identity$layout() {
        return worker_identity$LAYOUT;
    }

    private static final long worker_identity$OFFSET = $LAYOUT.byteOffset(groupElement("worker_identity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef worker_identity
     * }
     */
    public static final long worker_identity$offset() {
        return worker_identity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef worker_identity
     * }
     */
    public static MemorySegment worker_identity(MemorySegment struct) {
        return struct.asSlice(worker_identity$OFFSET, worker_identity$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef worker_identity
     * }
     */
    public static void worker_identity(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, worker_identity$OFFSET, worker_identity$LAYOUT.byteSize());
    }

    private static final GroupLayout worker_build_id$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("worker_build_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef worker_build_id
     * }
     */
    public static final GroupLayout worker_build_id$layout() {
        return worker_build_id$LAYOUT;
    }

    private static final long worker_build_id$OFFSET = $LAYOUT.byteOffset(groupElement("worker_build_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef worker_build_id
     * }
     */
    public static final long worker_build_id$offset() {
        return worker_build_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef worker_build_id
     * }
     */
    public static MemorySegment worker_build_id(MemorySegment struct) {
        return struct.asSlice(worker_build_id$OFFSET, worker_build_id$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef worker_build_id
     * }
     */
    public static void worker_build_id(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, worker_build_id$OFFSET, worker_build_id$LAYOUT.byteSize());
    }

    private static final OfBoolean is_sticky$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("is_sticky"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool is_sticky
     * }
     */
    public static final OfBoolean is_sticky$layout() {
        return is_sticky$LAYOUT;
    }

    private static final long is_sticky$OFFSET = $LAYOUT.byteOffset(groupElement("is_sticky"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool is_sticky
     * }
     */
    public static final long is_sticky$offset() {
        return is_sticky$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool is_sticky
     * }
     */
    public static boolean is_sticky(MemorySegment struct) {
        return struct.get(is_sticky$LAYOUT, is_sticky$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool is_sticky
     * }
     */
    public static void is_sticky(MemorySegment struct, boolean fieldValue) {
        struct.set(is_sticky$LAYOUT, is_sticky$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

