// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef const void *(*TemporalCoreCustomMetricMeterMetricNewCallback)(struct TemporalCoreByteArrayRef {
 *     const uint8_t *data;
 *     size_t size;
 * }, struct TemporalCoreByteArrayRef {
 *     const uint8_t *data;
 *     size_t size;
 * }, struct TemporalCoreByteArrayRef {
 *     const uint8_t *data;
 *     size_t size;
 * }, enum TemporalCoreMetricKind {
 *     CounterInteger = 1,
 *     HistogramInteger,
 *     HistogramFloat,
 *     HistogramDuration,
 *     GaugeInteger,
 *     GaugeFloat
 * })
 * }
 */
public final class TemporalCoreCustomMetricMeterMetricNewCallback {

    private TemporalCoreCustomMetricMeterMetricNewCallback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        MemorySegment apply(MemorySegment name, MemorySegment description, MemorySegment unit, int kind);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        temporal_sdk_core_c_bridge_h.C_POINTER,
        TemporalCoreByteArrayRef.layout(),
        TemporalCoreByteArrayRef.layout(),
        TemporalCoreByteArrayRef.layout(),
        temporal_sdk_core_c_bridge_h.C_INT
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = temporal_sdk_core_c_bridge_h.upcallHandle(TemporalCoreCustomMetricMeterMetricNewCallback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(TemporalCoreCustomMetricMeterMetricNewCallback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment name, MemorySegment description, MemorySegment unit, int kind) {
        try {
            return (MemorySegment) DOWN$MH.invokeExact(funcPtr, name, description, unit, kind);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

