// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreSlotReleaseCtx {
 *     const struct TemporalCoreSlotInfo *slot_info;
 *     uintptr_t slot_permit;
 * }
 * }
 */
public class TemporalCoreSlotReleaseCtx {

    TemporalCoreSlotReleaseCtx() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("slot_info"),
        temporal_sdk_core_c_bridge_h.C_LONG.withName("slot_permit")
    ).withName("TemporalCoreSlotReleaseCtx");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout slot_info$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("slot_info"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct TemporalCoreSlotInfo *slot_info
     * }
     */
    public static final AddressLayout slot_info$layout() {
        return slot_info$LAYOUT;
    }

    private static final long slot_info$OFFSET = $LAYOUT.byteOffset(groupElement("slot_info"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct TemporalCoreSlotInfo *slot_info
     * }
     */
    public static final long slot_info$offset() {
        return slot_info$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreSlotInfo *slot_info
     * }
     */
    public static MemorySegment slot_info(MemorySegment struct) {
        return struct.get(slot_info$LAYOUT, slot_info$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreSlotInfo *slot_info
     * }
     */
    public static void slot_info(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(slot_info$LAYOUT, slot_info$OFFSET, fieldValue);
    }

    private static final OfLong slot_permit$LAYOUT = (OfLong)$LAYOUT.select(groupElement("slot_permit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uintptr_t slot_permit
     * }
     */
    public static final OfLong slot_permit$layout() {
        return slot_permit$LAYOUT;
    }

    private static final long slot_permit$OFFSET = $LAYOUT.byteOffset(groupElement("slot_permit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uintptr_t slot_permit
     * }
     */
    public static final long slot_permit$offset() {
        return slot_permit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uintptr_t slot_permit
     * }
     */
    public static long slot_permit(MemorySegment struct) {
        return struct.get(slot_permit$LAYOUT, slot_permit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uintptr_t slot_permit
     * }
     */
    public static void slot_permit(MemorySegment struct, long fieldValue) {
        struct.set(slot_permit$LAYOUT, slot_permit$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

