// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreByteArray {
 *     const uint8_t *data;
 *     size_t size;
 *     size_t cap;
 *     bool disable_free;
 * }
 * }
 */
public class TemporalCoreByteArray {

    TemporalCoreByteArray() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("data"),
        temporal_sdk_core_c_bridge_h.C_LONG.withName("size"),
        temporal_sdk_core_c_bridge_h.C_LONG.withName("cap"),
        temporal_sdk_core_c_bridge_h.C_BOOL.withName("disable_free"),
        MemoryLayout.paddingLayout(7)
    ).withName("TemporalCoreByteArray");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const uint8_t *data
     * }
     */
    public static final AddressLayout data$layout() {
        return data$LAYOUT;
    }

    private static final long data$OFFSET = $LAYOUT.byteOffset(groupElement("data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const uint8_t *data
     * }
     */
    public static final long data$offset() {
        return data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const uint8_t *data
     * }
     */
    public static MemorySegment data(MemorySegment struct) {
        return struct.get(data$LAYOUT, data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const uint8_t *data
     * }
     */
    public static void data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(data$LAYOUT, data$OFFSET, fieldValue);
    }

    private static final OfLong size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static final OfLong size$layout() {
        return size$LAYOUT;
    }

    private static final long size$OFFSET = $LAYOUT.byteOffset(groupElement("size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static final long size$offset() {
        return size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static long size(MemorySegment struct) {
        return struct.get(size$LAYOUT, size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t size
     * }
     */
    public static void size(MemorySegment struct, long fieldValue) {
        struct.set(size$LAYOUT, size$OFFSET, fieldValue);
    }

    private static final OfLong cap$LAYOUT = (OfLong)$LAYOUT.select(groupElement("cap"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t cap
     * }
     */
    public static final OfLong cap$layout() {
        return cap$LAYOUT;
    }

    private static final long cap$OFFSET = $LAYOUT.byteOffset(groupElement("cap"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t cap
     * }
     */
    public static final long cap$offset() {
        return cap$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t cap
     * }
     */
    public static long cap(MemorySegment struct) {
        return struct.get(cap$LAYOUT, cap$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t cap
     * }
     */
    public static void cap(MemorySegment struct, long fieldValue) {
        struct.set(cap$LAYOUT, cap$OFFSET, fieldValue);
    }

    private static final OfBoolean disable_free$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("disable_free"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool disable_free
     * }
     */
    public static final OfBoolean disable_free$layout() {
        return disable_free$LAYOUT;
    }

    private static final long disable_free$OFFSET = $LAYOUT.byteOffset(groupElement("disable_free"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool disable_free
     * }
     */
    public static final long disable_free$offset() {
        return disable_free$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool disable_free
     * }
     */
    public static boolean disable_free(MemorySegment struct) {
        return struct.get(disable_free$LAYOUT, disable_free$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool disable_free
     * }
     */
    public static void disable_free(MemorySegment struct, boolean fieldValue) {
        struct.set(disable_free$LAYOUT, disable_free$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

