// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreOpenTelemetryOptions {
 *     struct TemporalCoreByteArrayRef url;
 *     TemporalCoreNewlineDelimitedMapRef headers;
 *     uint32_t metric_periodicity_millis;
 *     enum TemporalCoreOpenTelemetryMetricTemporality metric_temporality;
 *     bool durations_as_seconds;
 *     enum TemporalCoreOpenTelemetryProtocol protocol;
 *     TemporalCoreNewlineDelimitedMapRef histogram_bucket_overrides;
 * }
 * }
 */
public class TemporalCoreOpenTelemetryOptions {

    TemporalCoreOpenTelemetryOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TemporalCoreByteArrayRef.layout().withName("url"),
        TemporalCoreByteArrayRef.layout().withName("headers"),
        temporal_sdk_core_c_bridge_h.C_INT.withName("metric_periodicity_millis"),
        temporal_sdk_core_c_bridge_h.C_INT.withName("metric_temporality"),
        temporal_sdk_core_c_bridge_h.C_BOOL.withName("durations_as_seconds"),
        MemoryLayout.paddingLayout(3),
        temporal_sdk_core_c_bridge_h.C_INT.withName("protocol"),
        TemporalCoreByteArrayRef.layout().withName("histogram_bucket_overrides")
    ).withName("TemporalCoreOpenTelemetryOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout url$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("url"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef url
     * }
     */
    public static final GroupLayout url$layout() {
        return url$LAYOUT;
    }

    private static final long url$OFFSET = $LAYOUT.byteOffset(groupElement("url"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef url
     * }
     */
    public static final long url$offset() {
        return url$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef url
     * }
     */
    public static MemorySegment url(MemorySegment struct) {
        return struct.asSlice(url$OFFSET, url$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef url
     * }
     */
    public static void url(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, url$OFFSET, url$LAYOUT.byteSize());
    }

    private static final GroupLayout headers$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("headers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreNewlineDelimitedMapRef headers
     * }
     */
    public static final GroupLayout headers$layout() {
        return headers$LAYOUT;
    }

    private static final long headers$OFFSET = $LAYOUT.byteOffset(groupElement("headers"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreNewlineDelimitedMapRef headers
     * }
     */
    public static final long headers$offset() {
        return headers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreNewlineDelimitedMapRef headers
     * }
     */
    public static MemorySegment headers(MemorySegment struct) {
        return struct.asSlice(headers$OFFSET, headers$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreNewlineDelimitedMapRef headers
     * }
     */
    public static void headers(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, headers$OFFSET, headers$LAYOUT.byteSize());
    }

    private static final OfInt metric_periodicity_millis$LAYOUT = (OfInt)$LAYOUT.select(groupElement("metric_periodicity_millis"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t metric_periodicity_millis
     * }
     */
    public static final OfInt metric_periodicity_millis$layout() {
        return metric_periodicity_millis$LAYOUT;
    }

    private static final long metric_periodicity_millis$OFFSET = $LAYOUT.byteOffset(groupElement("metric_periodicity_millis"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t metric_periodicity_millis
     * }
     */
    public static final long metric_periodicity_millis$offset() {
        return metric_periodicity_millis$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t metric_periodicity_millis
     * }
     */
    public static int metric_periodicity_millis(MemorySegment struct) {
        return struct.get(metric_periodicity_millis$LAYOUT, metric_periodicity_millis$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t metric_periodicity_millis
     * }
     */
    public static void metric_periodicity_millis(MemorySegment struct, int fieldValue) {
        struct.set(metric_periodicity_millis$LAYOUT, metric_periodicity_millis$OFFSET, fieldValue);
    }

    private static final OfInt metric_temporality$LAYOUT = (OfInt)$LAYOUT.select(groupElement("metric_temporality"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum TemporalCoreOpenTelemetryMetricTemporality metric_temporality
     * }
     */
    public static final OfInt metric_temporality$layout() {
        return metric_temporality$LAYOUT;
    }

    private static final long metric_temporality$OFFSET = $LAYOUT.byteOffset(groupElement("metric_temporality"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum TemporalCoreOpenTelemetryMetricTemporality metric_temporality
     * }
     */
    public static final long metric_temporality$offset() {
        return metric_temporality$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum TemporalCoreOpenTelemetryMetricTemporality metric_temporality
     * }
     */
    public static int metric_temporality(MemorySegment struct) {
        return struct.get(metric_temporality$LAYOUT, metric_temporality$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum TemporalCoreOpenTelemetryMetricTemporality metric_temporality
     * }
     */
    public static void metric_temporality(MemorySegment struct, int fieldValue) {
        struct.set(metric_temporality$LAYOUT, metric_temporality$OFFSET, fieldValue);
    }

    private static final OfBoolean durations_as_seconds$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("durations_as_seconds"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool durations_as_seconds
     * }
     */
    public static final OfBoolean durations_as_seconds$layout() {
        return durations_as_seconds$LAYOUT;
    }

    private static final long durations_as_seconds$OFFSET = $LAYOUT.byteOffset(groupElement("durations_as_seconds"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool durations_as_seconds
     * }
     */
    public static final long durations_as_seconds$offset() {
        return durations_as_seconds$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool durations_as_seconds
     * }
     */
    public static boolean durations_as_seconds(MemorySegment struct) {
        return struct.get(durations_as_seconds$LAYOUT, durations_as_seconds$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool durations_as_seconds
     * }
     */
    public static void durations_as_seconds(MemorySegment struct, boolean fieldValue) {
        struct.set(durations_as_seconds$LAYOUT, durations_as_seconds$OFFSET, fieldValue);
    }

    private static final OfInt protocol$LAYOUT = (OfInt)$LAYOUT.select(groupElement("protocol"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum TemporalCoreOpenTelemetryProtocol protocol
     * }
     */
    public static final OfInt protocol$layout() {
        return protocol$LAYOUT;
    }

    private static final long protocol$OFFSET = $LAYOUT.byteOffset(groupElement("protocol"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum TemporalCoreOpenTelemetryProtocol protocol
     * }
     */
    public static final long protocol$offset() {
        return protocol$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum TemporalCoreOpenTelemetryProtocol protocol
     * }
     */
    public static int protocol(MemorySegment struct) {
        return struct.get(protocol$LAYOUT, protocol$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum TemporalCoreOpenTelemetryProtocol protocol
     * }
     */
    public static void protocol(MemorySegment struct, int fieldValue) {
        struct.set(protocol$LAYOUT, protocol$OFFSET, fieldValue);
    }

    private static final GroupLayout histogram_bucket_overrides$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("histogram_bucket_overrides"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreNewlineDelimitedMapRef histogram_bucket_overrides
     * }
     */
    public static final GroupLayout histogram_bucket_overrides$layout() {
        return histogram_bucket_overrides$LAYOUT;
    }

    private static final long histogram_bucket_overrides$OFFSET = $LAYOUT.byteOffset(groupElement("histogram_bucket_overrides"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreNewlineDelimitedMapRef histogram_bucket_overrides
     * }
     */
    public static final long histogram_bucket_overrides$offset() {
        return histogram_bucket_overrides$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreNewlineDelimitedMapRef histogram_bucket_overrides
     * }
     */
    public static MemorySegment histogram_bucket_overrides(MemorySegment struct) {
        return struct.asSlice(histogram_bucket_overrides$OFFSET, histogram_bucket_overrides$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreNewlineDelimitedMapRef histogram_bucket_overrides
     * }
     */
    public static void histogram_bucket_overrides(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, histogram_bucket_overrides$OFFSET, histogram_bucket_overrides$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

