// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreClientRetryOptions {
 *     uint64_t initial_interval_millis;
 *     double randomization_factor;
 *     double multiplier;
 *     uint64_t max_interval_millis;
 *     uint64_t max_elapsed_time_millis;
 *     uintptr_t max_retries;
 * }
 * }
 */
public class TemporalCoreClientRetryOptions {

    TemporalCoreClientRetryOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_LONG_LONG.withName("initial_interval_millis"),
        temporal_sdk_core_c_bridge_h.C_DOUBLE.withName("randomization_factor"),
        temporal_sdk_core_c_bridge_h.C_DOUBLE.withName("multiplier"),
        temporal_sdk_core_c_bridge_h.C_LONG_LONG.withName("max_interval_millis"),
        temporal_sdk_core_c_bridge_h.C_LONG_LONG.withName("max_elapsed_time_millis"),
        temporal_sdk_core_c_bridge_h.C_LONG.withName("max_retries")
    ).withName("TemporalCoreClientRetryOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong initial_interval_millis$LAYOUT = (OfLong)$LAYOUT.select(groupElement("initial_interval_millis"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t initial_interval_millis
     * }
     */
    public static final OfLong initial_interval_millis$layout() {
        return initial_interval_millis$LAYOUT;
    }

    private static final long initial_interval_millis$OFFSET = $LAYOUT.byteOffset(groupElement("initial_interval_millis"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t initial_interval_millis
     * }
     */
    public static final long initial_interval_millis$offset() {
        return initial_interval_millis$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t initial_interval_millis
     * }
     */
    public static long initial_interval_millis(MemorySegment struct) {
        return struct.get(initial_interval_millis$LAYOUT, initial_interval_millis$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t initial_interval_millis
     * }
     */
    public static void initial_interval_millis(MemorySegment struct, long fieldValue) {
        struct.set(initial_interval_millis$LAYOUT, initial_interval_millis$OFFSET, fieldValue);
    }

    private static final OfDouble randomization_factor$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("randomization_factor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double randomization_factor
     * }
     */
    public static final OfDouble randomization_factor$layout() {
        return randomization_factor$LAYOUT;
    }

    private static final long randomization_factor$OFFSET = $LAYOUT.byteOffset(groupElement("randomization_factor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double randomization_factor
     * }
     */
    public static final long randomization_factor$offset() {
        return randomization_factor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double randomization_factor
     * }
     */
    public static double randomization_factor(MemorySegment struct) {
        return struct.get(randomization_factor$LAYOUT, randomization_factor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double randomization_factor
     * }
     */
    public static void randomization_factor(MemorySegment struct, double fieldValue) {
        struct.set(randomization_factor$LAYOUT, randomization_factor$OFFSET, fieldValue);
    }

    private static final OfDouble multiplier$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("multiplier"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double multiplier
     * }
     */
    public static final OfDouble multiplier$layout() {
        return multiplier$LAYOUT;
    }

    private static final long multiplier$OFFSET = $LAYOUT.byteOffset(groupElement("multiplier"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double multiplier
     * }
     */
    public static final long multiplier$offset() {
        return multiplier$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double multiplier
     * }
     */
    public static double multiplier(MemorySegment struct) {
        return struct.get(multiplier$LAYOUT, multiplier$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double multiplier
     * }
     */
    public static void multiplier(MemorySegment struct, double fieldValue) {
        struct.set(multiplier$LAYOUT, multiplier$OFFSET, fieldValue);
    }

    private static final OfLong max_interval_millis$LAYOUT = (OfLong)$LAYOUT.select(groupElement("max_interval_millis"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t max_interval_millis
     * }
     */
    public static final OfLong max_interval_millis$layout() {
        return max_interval_millis$LAYOUT;
    }

    private static final long max_interval_millis$OFFSET = $LAYOUT.byteOffset(groupElement("max_interval_millis"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t max_interval_millis
     * }
     */
    public static final long max_interval_millis$offset() {
        return max_interval_millis$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t max_interval_millis
     * }
     */
    public static long max_interval_millis(MemorySegment struct) {
        return struct.get(max_interval_millis$LAYOUT, max_interval_millis$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t max_interval_millis
     * }
     */
    public static void max_interval_millis(MemorySegment struct, long fieldValue) {
        struct.set(max_interval_millis$LAYOUT, max_interval_millis$OFFSET, fieldValue);
    }

    private static final OfLong max_elapsed_time_millis$LAYOUT = (OfLong)$LAYOUT.select(groupElement("max_elapsed_time_millis"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t max_elapsed_time_millis
     * }
     */
    public static final OfLong max_elapsed_time_millis$layout() {
        return max_elapsed_time_millis$LAYOUT;
    }

    private static final long max_elapsed_time_millis$OFFSET = $LAYOUT.byteOffset(groupElement("max_elapsed_time_millis"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t max_elapsed_time_millis
     * }
     */
    public static final long max_elapsed_time_millis$offset() {
        return max_elapsed_time_millis$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t max_elapsed_time_millis
     * }
     */
    public static long max_elapsed_time_millis(MemorySegment struct) {
        return struct.get(max_elapsed_time_millis$LAYOUT, max_elapsed_time_millis$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t max_elapsed_time_millis
     * }
     */
    public static void max_elapsed_time_millis(MemorySegment struct, long fieldValue) {
        struct.set(max_elapsed_time_millis$LAYOUT, max_elapsed_time_millis$OFFSET, fieldValue);
    }

    private static final OfLong max_retries$LAYOUT = (OfLong)$LAYOUT.select(groupElement("max_retries"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uintptr_t max_retries
     * }
     */
    public static final OfLong max_retries$layout() {
        return max_retries$LAYOUT;
    }

    private static final long max_retries$OFFSET = $LAYOUT.byteOffset(groupElement("max_retries"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uintptr_t max_retries
     * }
     */
    public static final long max_retries$offset() {
        return max_retries$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uintptr_t max_retries
     * }
     */
    public static long max_retries(MemorySegment struct) {
        return struct.get(max_retries$LAYOUT, max_retries$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uintptr_t max_retries
     * }
     */
    public static void max_retries(MemorySegment struct, long fieldValue) {
        struct.set(max_retries$LAYOUT, max_retries$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

