// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreClientHttpConnectProxyOptions {
 *     struct TemporalCoreByteArrayRef target_host;
 *     struct TemporalCoreByteArrayRef username;
 *     struct TemporalCoreByteArrayRef password;
 * }
 * }
 */
public class TemporalCoreClientHttpConnectProxyOptions {

    TemporalCoreClientHttpConnectProxyOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TemporalCoreByteArrayRef.layout().withName("target_host"),
        TemporalCoreByteArrayRef.layout().withName("username"),
        TemporalCoreByteArrayRef.layout().withName("password")
    ).withName("TemporalCoreClientHttpConnectProxyOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout target_host$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("target_host"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef target_host
     * }
     */
    public static final GroupLayout target_host$layout() {
        return target_host$LAYOUT;
    }

    private static final long target_host$OFFSET = $LAYOUT.byteOffset(groupElement("target_host"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef target_host
     * }
     */
    public static final long target_host$offset() {
        return target_host$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef target_host
     * }
     */
    public static MemorySegment target_host(MemorySegment struct) {
        return struct.asSlice(target_host$OFFSET, target_host$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef target_host
     * }
     */
    public static void target_host(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, target_host$OFFSET, target_host$LAYOUT.byteSize());
    }

    private static final GroupLayout username$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("username"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef username
     * }
     */
    public static final GroupLayout username$layout() {
        return username$LAYOUT;
    }

    private static final long username$OFFSET = $LAYOUT.byteOffset(groupElement("username"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef username
     * }
     */
    public static final long username$offset() {
        return username$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef username
     * }
     */
    public static MemorySegment username(MemorySegment struct) {
        return struct.asSlice(username$OFFSET, username$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef username
     * }
     */
    public static void username(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, username$OFFSET, username$LAYOUT.byteSize());
    }

    private static final GroupLayout password$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("password"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef password
     * }
     */
    public static final GroupLayout password$layout() {
        return password$LAYOUT;
    }

    private static final long password$OFFSET = $LAYOUT.byteOffset(groupElement("password"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef password
     * }
     */
    public static final long password$offset() {
        return password$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef password
     * }
     */
    public static MemorySegment password(MemorySegment struct) {
        return struct.asSlice(password$OFFSET, password$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef password
     * }
     */
    public static void password(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, password$OFFSET, password$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

