// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreClientTlsOptions {
 *     struct TemporalCoreByteArrayRef server_root_ca_cert;
 *     struct TemporalCoreByteArrayRef domain;
 *     struct TemporalCoreByteArrayRef client_cert;
 *     struct TemporalCoreByteArrayRef client_private_key;
 * }
 * }
 */
public class TemporalCoreClientTlsOptions {

    TemporalCoreClientTlsOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TemporalCoreByteArrayRef.layout().withName("server_root_ca_cert"),
        TemporalCoreByteArrayRef.layout().withName("domain"),
        TemporalCoreByteArrayRef.layout().withName("client_cert"),
        TemporalCoreByteArrayRef.layout().withName("client_private_key")
    ).withName("TemporalCoreClientTlsOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout server_root_ca_cert$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("server_root_ca_cert"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef server_root_ca_cert
     * }
     */
    public static final GroupLayout server_root_ca_cert$layout() {
        return server_root_ca_cert$LAYOUT;
    }

    private static final long server_root_ca_cert$OFFSET = $LAYOUT.byteOffset(groupElement("server_root_ca_cert"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef server_root_ca_cert
     * }
     */
    public static final long server_root_ca_cert$offset() {
        return server_root_ca_cert$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef server_root_ca_cert
     * }
     */
    public static MemorySegment server_root_ca_cert(MemorySegment struct) {
        return struct.asSlice(server_root_ca_cert$OFFSET, server_root_ca_cert$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef server_root_ca_cert
     * }
     */
    public static void server_root_ca_cert(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, server_root_ca_cert$OFFSET, server_root_ca_cert$LAYOUT.byteSize());
    }

    private static final GroupLayout domain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("domain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef domain
     * }
     */
    public static final GroupLayout domain$layout() {
        return domain$LAYOUT;
    }

    private static final long domain$OFFSET = $LAYOUT.byteOffset(groupElement("domain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef domain
     * }
     */
    public static final long domain$offset() {
        return domain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef domain
     * }
     */
    public static MemorySegment domain(MemorySegment struct) {
        return struct.asSlice(domain$OFFSET, domain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef domain
     * }
     */
    public static void domain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, domain$OFFSET, domain$LAYOUT.byteSize());
    }

    private static final GroupLayout client_cert$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("client_cert"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef client_cert
     * }
     */
    public static final GroupLayout client_cert$layout() {
        return client_cert$LAYOUT;
    }

    private static final long client_cert$OFFSET = $LAYOUT.byteOffset(groupElement("client_cert"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef client_cert
     * }
     */
    public static final long client_cert$offset() {
        return client_cert$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef client_cert
     * }
     */
    public static MemorySegment client_cert(MemorySegment struct) {
        return struct.asSlice(client_cert$OFFSET, client_cert$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef client_cert
     * }
     */
    public static void client_cert(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, client_cert$OFFSET, client_cert$LAYOUT.byteSize());
    }

    private static final GroupLayout client_private_key$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("client_private_key"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef client_private_key
     * }
     */
    public static final GroupLayout client_private_key$layout() {
        return client_private_key$LAYOUT;
    }

    private static final long client_private_key$OFFSET = $LAYOUT.byteOffset(groupElement("client_private_key"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef client_private_key
     * }
     */
    public static final long client_private_key$offset() {
        return client_private_key$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef client_private_key
     * }
     */
    public static MemorySegment client_private_key(MemorySegment struct) {
        return struct.asSlice(client_private_key$OFFSET, client_private_key$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef client_private_key
     * }
     */
    public static void client_private_key(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, client_private_key$OFFSET, client_private_key$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

