// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreLoggingOptions {
 *     struct TemporalCoreByteArrayRef filter;
 *     TemporalCoreForwardedLogCallback forward_to;
 * }
 * }
 */
public class TemporalCoreLoggingOptions {

    TemporalCoreLoggingOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TemporalCoreByteArrayRef.layout().withName("filter"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("forward_to")
    ).withName("TemporalCoreLoggingOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout filter$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("filter"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef filter
     * }
     */
    public static final GroupLayout filter$layout() {
        return filter$LAYOUT;
    }

    private static final long filter$OFFSET = $LAYOUT.byteOffset(groupElement("filter"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef filter
     * }
     */
    public static final long filter$offset() {
        return filter$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef filter
     * }
     */
    public static MemorySegment filter(MemorySegment struct) {
        return struct.asSlice(filter$OFFSET, filter$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef filter
     * }
     */
    public static void filter(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, filter$OFFSET, filter$LAYOUT.byteSize());
    }

    private static final AddressLayout forward_to$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("forward_to"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreForwardedLogCallback forward_to
     * }
     */
    public static final AddressLayout forward_to$layout() {
        return forward_to$LAYOUT;
    }

    private static final long forward_to$OFFSET = $LAYOUT.byteOffset(groupElement("forward_to"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreForwardedLogCallback forward_to
     * }
     */
    public static final long forward_to$offset() {
        return forward_to$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreForwardedLogCallback forward_to
     * }
     */
    public static MemorySegment forward_to(MemorySegment struct) {
        return struct.get(forward_to$LAYOUT, forward_to$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreForwardedLogCallback forward_to
     * }
     */
    public static void forward_to(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(forward_to$LAYOUT, forward_to$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

