// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreResourceBasedSlotSupplier {
 *     uintptr_t minimum_slots;
 *     uintptr_t maximum_slots;
 *     uint64_t ramp_throttle_ms;
 *     struct TemporalCoreResourceBasedTunerOptions tuner_options;
 * }
 * }
 */
public class TemporalCoreResourceBasedSlotSupplier {

    TemporalCoreResourceBasedSlotSupplier() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_LONG.withName("minimum_slots"),
        temporal_sdk_core_c_bridge_h.C_LONG.withName("maximum_slots"),
        temporal_sdk_core_c_bridge_h.C_LONG_LONG.withName("ramp_throttle_ms"),
        TemporalCoreResourceBasedTunerOptions.layout().withName("tuner_options")
    ).withName("TemporalCoreResourceBasedSlotSupplier");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong minimum_slots$LAYOUT = (OfLong)$LAYOUT.select(groupElement("minimum_slots"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uintptr_t minimum_slots
     * }
     */
    public static final OfLong minimum_slots$layout() {
        return minimum_slots$LAYOUT;
    }

    private static final long minimum_slots$OFFSET = $LAYOUT.byteOffset(groupElement("minimum_slots"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uintptr_t minimum_slots
     * }
     */
    public static final long minimum_slots$offset() {
        return minimum_slots$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uintptr_t minimum_slots
     * }
     */
    public static long minimum_slots(MemorySegment struct) {
        return struct.get(minimum_slots$LAYOUT, minimum_slots$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uintptr_t minimum_slots
     * }
     */
    public static void minimum_slots(MemorySegment struct, long fieldValue) {
        struct.set(minimum_slots$LAYOUT, minimum_slots$OFFSET, fieldValue);
    }

    private static final OfLong maximum_slots$LAYOUT = (OfLong)$LAYOUT.select(groupElement("maximum_slots"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uintptr_t maximum_slots
     * }
     */
    public static final OfLong maximum_slots$layout() {
        return maximum_slots$LAYOUT;
    }

    private static final long maximum_slots$OFFSET = $LAYOUT.byteOffset(groupElement("maximum_slots"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uintptr_t maximum_slots
     * }
     */
    public static final long maximum_slots$offset() {
        return maximum_slots$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uintptr_t maximum_slots
     * }
     */
    public static long maximum_slots(MemorySegment struct) {
        return struct.get(maximum_slots$LAYOUT, maximum_slots$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uintptr_t maximum_slots
     * }
     */
    public static void maximum_slots(MemorySegment struct, long fieldValue) {
        struct.set(maximum_slots$LAYOUT, maximum_slots$OFFSET, fieldValue);
    }

    private static final OfLong ramp_throttle_ms$LAYOUT = (OfLong)$LAYOUT.select(groupElement("ramp_throttle_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t ramp_throttle_ms
     * }
     */
    public static final OfLong ramp_throttle_ms$layout() {
        return ramp_throttle_ms$LAYOUT;
    }

    private static final long ramp_throttle_ms$OFFSET = $LAYOUT.byteOffset(groupElement("ramp_throttle_ms"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t ramp_throttle_ms
     * }
     */
    public static final long ramp_throttle_ms$offset() {
        return ramp_throttle_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t ramp_throttle_ms
     * }
     */
    public static long ramp_throttle_ms(MemorySegment struct) {
        return struct.get(ramp_throttle_ms$LAYOUT, ramp_throttle_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t ramp_throttle_ms
     * }
     */
    public static void ramp_throttle_ms(MemorySegment struct, long fieldValue) {
        struct.set(ramp_throttle_ms$LAYOUT, ramp_throttle_ms$OFFSET, fieldValue);
    }

    private static final GroupLayout tuner_options$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("tuner_options"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreResourceBasedTunerOptions tuner_options
     * }
     */
    public static final GroupLayout tuner_options$layout() {
        return tuner_options$LAYOUT;
    }

    private static final long tuner_options$OFFSET = $LAYOUT.byteOffset(groupElement("tuner_options"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreResourceBasedTunerOptions tuner_options
     * }
     */
    public static final long tuner_options$offset() {
        return tuner_options$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreResourceBasedTunerOptions tuner_options
     * }
     */
    public static MemorySegment tuner_options(MemorySegment struct) {
        return struct.asSlice(tuner_options$OFFSET, tuner_options$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreResourceBasedTunerOptions tuner_options
     * }
     */
    public static void tuner_options(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, tuner_options$OFFSET, tuner_options$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

