// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreWorkerVersioningStrategy {
 *     TemporalCoreWorkerVersioningStrategy_Tag tag;
 *     union {
 *         struct {
 *             struct TemporalCoreWorkerVersioningNone none;
 *         };
 *         struct {
 *             struct TemporalCoreWorkerDeploymentOptions deployment_based;
 *         };
 *         struct {
 *             struct TemporalCoreLegacyBuildIdBasedStrategy legacy_build_id_based;
 *         };
 *     };
 * }
 * }
 */
public class TemporalCoreWorkerVersioningStrategy {

    TemporalCoreWorkerVersioningStrategy() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_INT.withName("tag"),
        MemoryLayout.paddingLayout(4),
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                TemporalCoreWorkerVersioningNone.layout().withName("none")
            ).withName("$anon$555:5"),
            MemoryLayout.structLayout(
                TemporalCoreWorkerDeploymentOptions.layout().withName("deployment_based")
            ).withName("$anon$558:5"),
            MemoryLayout.structLayout(
                TemporalCoreLegacyBuildIdBasedStrategy.layout().withName("legacy_build_id_based")
            ).withName("$anon$561:5")
        ).withName("$anon$554:3")
    ).withName("TemporalCoreWorkerVersioningStrategy");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt tag$LAYOUT = (OfInt)$LAYOUT.select(groupElement("tag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreWorkerVersioningStrategy_Tag tag
     * }
     */
    public static final OfInt tag$layout() {
        return tag$LAYOUT;
    }

    private static final long tag$OFFSET = $LAYOUT.byteOffset(groupElement("tag"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreWorkerVersioningStrategy_Tag tag
     * }
     */
    public static final long tag$offset() {
        return tag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreWorkerVersioningStrategy_Tag tag
     * }
     */
    public static int tag(MemorySegment struct) {
        return struct.get(tag$LAYOUT, tag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreWorkerVersioningStrategy_Tag tag
     * }
     */
    public static void tag(MemorySegment struct, int fieldValue) {
        struct.set(tag$LAYOUT, tag$OFFSET, fieldValue);
    }

    private static final GroupLayout none$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$554:3"), groupElement("$anon$555:5"), groupElement("none"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreWorkerVersioningNone none
     * }
     */
    public static final GroupLayout none$layout() {
        return none$LAYOUT;
    }

    private static final long none$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$554:3"), groupElement("$anon$555:5"), groupElement("none"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreWorkerVersioningNone none
     * }
     */
    public static final long none$offset() {
        return none$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreWorkerVersioningNone none
     * }
     */
    public static MemorySegment none(MemorySegment struct) {
        return struct.asSlice(none$OFFSET, none$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreWorkerVersioningNone none
     * }
     */
    public static void none(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, none$OFFSET, none$LAYOUT.byteSize());
    }

    private static final GroupLayout deployment_based$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$554:3"), groupElement("$anon$558:5"), groupElement("deployment_based"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreWorkerDeploymentOptions deployment_based
     * }
     */
    public static final GroupLayout deployment_based$layout() {
        return deployment_based$LAYOUT;
    }

    private static final long deployment_based$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$554:3"), groupElement("$anon$558:5"), groupElement("deployment_based"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreWorkerDeploymentOptions deployment_based
     * }
     */
    public static final long deployment_based$offset() {
        return deployment_based$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreWorkerDeploymentOptions deployment_based
     * }
     */
    public static MemorySegment deployment_based(MemorySegment struct) {
        return struct.asSlice(deployment_based$OFFSET, deployment_based$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreWorkerDeploymentOptions deployment_based
     * }
     */
    public static void deployment_based(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, deployment_based$OFFSET, deployment_based$LAYOUT.byteSize());
    }

    private static final GroupLayout legacy_build_id_based$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$554:3"), groupElement("$anon$561:5"), groupElement("legacy_build_id_based"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreLegacyBuildIdBasedStrategy legacy_build_id_based
     * }
     */
    public static final GroupLayout legacy_build_id_based$layout() {
        return legacy_build_id_based$LAYOUT;
    }

    private static final long legacy_build_id_based$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$554:3"), groupElement("$anon$561:5"), groupElement("legacy_build_id_based"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreLegacyBuildIdBasedStrategy legacy_build_id_based
     * }
     */
    public static final long legacy_build_id_based$offset() {
        return legacy_build_id_based$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreLegacyBuildIdBasedStrategy legacy_build_id_based
     * }
     */
    public static MemorySegment legacy_build_id_based(MemorySegment struct) {
        return struct.asSlice(legacy_build_id_based$OFFSET, legacy_build_id_based$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreLegacyBuildIdBasedStrategy legacy_build_id_based
     * }
     */
    public static void legacy_build_id_based(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, legacy_build_id_based$OFFSET, legacy_build_id_based$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

