// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreWorkerDeploymentOptions {
 *     struct TemporalCoreWorkerDeploymentVersion version;
 *     bool use_worker_versioning;
 *     int32_t default_versioning_behavior;
 * }
 * }
 */
public class TemporalCoreWorkerDeploymentOptions {

    TemporalCoreWorkerDeploymentOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TemporalCoreWorkerDeploymentVersion.layout().withName("version"),
        temporal_sdk_core_c_bridge_h.C_BOOL.withName("use_worker_versioning"),
        MemoryLayout.paddingLayout(3),
        temporal_sdk_core_c_bridge_h.C_INT.withName("default_versioning_behavior")
    ).withName("TemporalCoreWorkerDeploymentOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout version$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreWorkerDeploymentVersion version
     * }
     */
    public static final GroupLayout version$layout() {
        return version$LAYOUT;
    }

    private static final long version$OFFSET = $LAYOUT.byteOffset(groupElement("version"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreWorkerDeploymentVersion version
     * }
     */
    public static final long version$offset() {
        return version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreWorkerDeploymentVersion version
     * }
     */
    public static MemorySegment version(MemorySegment struct) {
        return struct.asSlice(version$OFFSET, version$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreWorkerDeploymentVersion version
     * }
     */
    public static void version(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, version$OFFSET, version$LAYOUT.byteSize());
    }

    private static final OfBoolean use_worker_versioning$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("use_worker_versioning"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool use_worker_versioning
     * }
     */
    public static final OfBoolean use_worker_versioning$layout() {
        return use_worker_versioning$LAYOUT;
    }

    private static final long use_worker_versioning$OFFSET = $LAYOUT.byteOffset(groupElement("use_worker_versioning"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool use_worker_versioning
     * }
     */
    public static final long use_worker_versioning$offset() {
        return use_worker_versioning$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool use_worker_versioning
     * }
     */
    public static boolean use_worker_versioning(MemorySegment struct) {
        return struct.get(use_worker_versioning$LAYOUT, use_worker_versioning$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool use_worker_versioning
     * }
     */
    public static void use_worker_versioning(MemorySegment struct, boolean fieldValue) {
        struct.set(use_worker_versioning$LAYOUT, use_worker_versioning$OFFSET, fieldValue);
    }

    private static final OfInt default_versioning_behavior$LAYOUT = (OfInt)$LAYOUT.select(groupElement("default_versioning_behavior"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t default_versioning_behavior
     * }
     */
    public static final OfInt default_versioning_behavior$layout() {
        return default_versioning_behavior$LAYOUT;
    }

    private static final long default_versioning_behavior$OFFSET = $LAYOUT.byteOffset(groupElement("default_versioning_behavior"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t default_versioning_behavior
     * }
     */
    public static final long default_versioning_behavior$offset() {
        return default_versioning_behavior$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t default_versioning_behavior
     * }
     */
    public static int default_versioning_behavior(MemorySegment struct) {
        return struct.get(default_versioning_behavior$LAYOUT, default_versioning_behavior$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t default_versioning_behavior
     * }
     */
    public static void default_versioning_behavior(MemorySegment struct, int fieldValue) {
        struct.set(default_versioning_behavior$LAYOUT, default_versioning_behavior$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

